
sudo: required
dist: trusty
language: node_js
node_js:
  - "9.5"

before_script:
  - npm i npm@latest -g
  - npm install -g --silent @angular/cli@6.2.3

script:
  - ng lint
  - ng build --prod --output-hashing=none --base-href="/web-app/"

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist/web-app
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
