
sudo: required
dist: trusty
language: node_js
node_js:
  - "lts/*"

before_script:
  - npm i npm@latest -g
  - npm install -g --silent @angular/cli@9.1.12

script:
  - ng lint
  - npm run build:prod

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist/web-app
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
