/** Angular Imports */
import { NgModule } from '@angular/core';

/** Angular Font Awesome Imports */
import { FontAwesomeModule, FaIconLibrary } from '@fortawesome/angular-fontawesome';
import {
  faAnchor,
  faArchive,
  faArrowLeft,
  faArrowRight,
  faBars,
  faBell,
  faBook,
  faBriefcase,
  faBuilding,
  faCalendar,
  faCalendarAlt,
  faChartBar,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faClock,
  faCloud,
  faCog,
  faCogs,
  faCommentAlt,
  faDollarSign,
  faEdit,
  faEnvelope,
  faExclamationCircle,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faFile,
  faFileAlt,
  faFileUpload,
  faFileWord,
  faFillDrip,
  faHandHoldingUsd,
  faHome,
  faKey,
  faLink,
  faList,
  faListUl,
  faLocationArrow,
  faLock,
  faLockOpen,
  faMinusCircle,
  faMinus,
  faMoneyBillAlt,
  faMoneyCheck,
  faPencilAlt,
  faPlay,
  faPlus,
  faPlusCircle,
  faQuestionCircle,
  faRandom,
  faRoad,
  faSearch,
  faShieldAlt,
  faSignOutAlt,
  faSitemap,
  faSync,
  faTable,
  faTachometerAlt,
  faTag,
  faTags,
  faTimesCircle,
  faTrash,
  faUndo,
  faUniversity,
  faUserCircle,
  faUser,
  faUsers,
  faUserShield,
  faDownload,
  faUpload,
  faCloudDownloadAlt,
  faCloudUploadAlt,
  faTimes,
  faStickyNote,
  faStop,
  faBan,
  faBolt,
  faLaptop,
  faDonate,
  faMoneyBill,
  faChartLine,
  faPen,
  faFlag,
  faArrowUp,
  faArrowDown,
  faFolderOpen,
  faIdBadge,
  faAddressCard,
  faKeyboard
} from '@fortawesome/free-solid-svg-icons';

/**
 * Icons Module
 *
 * Angular Font Awesome module is exported here.
 */
@NgModule({
  exports: [FontAwesomeModule]
})
export class IconsModule {

  constructor(library: FaIconLibrary) {
    library.addIcons(
      faAnchor as any,
      faArchive as any,
      faArrowLeft as any,
      faArrowRight as any,
      faBars as any,
      faBell as any,
      faBook as any,
      faBriefcase as any,
      faBuilding as any,
      faCalendar as any,
      faCalendarAlt as any,
      faChartBar as any,
      faCheck as any,
      faCheckCircle as any,
      faChevronDown as any,
      faChevronLeft as any,
      faChevronRight as any,
      faCircle as any,
      faClock as any,
      faCloud as any,
      faCog as any,
      faCogs as any,
      faCommentAlt as any,
      faDollarSign as any,
      faEdit as any,
      faEnvelope as any,
      faExclamationCircle as any,
      faExclamationTriangle as any,
      faEye as any,
      faEyeSlash as any,
      faFile as any,
      faFileAlt as any,
      faFileUpload as any,
      faFileWord as any,
      faFillDrip as any,
      faHandHoldingUsd as any,
      faHome as any,
      faKey as any,
      faLink as any,
      faList as any,
      faListUl as any,
      faLocationArrow as any,
      faLock as any,
      faLockOpen as any,
      faMinus as any,
      faMinusCircle as any,
      faMoneyBillAlt as any,
      faMoneyCheck as any,
      faPencilAlt as any,
      faPlay as any,
      faPlus as any,
      faPlusCircle as any,
      faQuestionCircle as any,
      faRandom as any,
      faRoad as any,
      faSearch as any,
      faShieldAlt as any,
      faSignOutAlt as any,
      faSitemap as any,
      faSync as any,
      faTable as any,
      faTachometerAlt as any,
      faTag as any,
      faTags as any,
      faTimesCircle as any,
      faTrash as any,
      faUndo as any,
      faUniversity as any,
      faUserCircle as any,
      faUser as any,
      faUsers as any,
      faUserShield as any,
      faDownload as any,
      faUpload as any,
      faCloudDownloadAlt as any,
      faCloudUploadAlt as any,
      faTimes as any,
      faStickyNote as any,
      faStop as any,
      faBan as any,
      faBolt as any,
      faLaptop as any,
      faDonate as any,
      faMoneyBill as any,
      faChartLine as any,
      faPen as any,
      faFlag as any,
      faArrowUp as any,
      faArrowDown as any,
      faFolderOpen as any,
      faIdBadge as any,
      faAddressCard as any,
      faKeyboard as any
    ) 
  }

}
