/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
  HttpContext
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

export interface AddClientFamilyMembersRequestParams {
  clientId: number;
  body?: string;
}

export interface DeleteClientFamilyMembersRequestParams {
  familyMemberId: number;
  /** clientId */
  clientId: number;
  body?: string;
}

export interface GetFamilyMemberRequestParams {
  familyMemberId: number;
  /** clientId */
  clientId: number;
}

export interface GetFamilyMembersRequestParams {
  clientId: number;
}

export interface GetTemplate2RequestParams {
  clientId: number;
}

export interface UpdateClientFamilyMembersRequestParams {
  familyMemberId: number;
  /** clientId */
  clientId: number;
  body?: string;
}

@Injectable({
  providedIn: 'root'
})
export class ClientFamilyMemberService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration
  ) {
    super(basePath, configuration);
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public addClientFamilyMembers(
    requestParameters: AddClientFamilyMembersRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public addClientFamilyMembers(
    requestParameters: AddClientFamilyMembersRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public addClientFamilyMembers(
    requestParameters: AddClientFamilyMembersRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public addClientFamilyMembers(
    requestParameters: AddClientFamilyMembersRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const clientId = requestParameters?.clientId;
    if (clientId === null || clientId === undefined) {
      throw new Error('Required parameter clientId was null or undefined when calling addClientFamilyMembers.');
    }
    const body = requestParameters?.body;

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/clients/${this.configuration.encodeParam({ name: 'clientId', value: clientId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/familymembers`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: body,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteClientFamilyMembers(
    requestParameters: DeleteClientFamilyMembersRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public deleteClientFamilyMembers(
    requestParameters: DeleteClientFamilyMembersRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public deleteClientFamilyMembers(
    requestParameters: DeleteClientFamilyMembersRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public deleteClientFamilyMembers(
    requestParameters: DeleteClientFamilyMembersRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const familyMemberId = requestParameters?.familyMemberId;
    if (familyMemberId === null || familyMemberId === undefined) {
      throw new Error(
        'Required parameter familyMemberId was null or undefined when calling deleteClientFamilyMembers.'
      );
    }
    const clientId = requestParameters?.clientId;
    if (clientId === null || clientId === undefined) {
      throw new Error('Required parameter clientId was null or undefined when calling deleteClientFamilyMembers.');
    }
    const body = requestParameters?.body;

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/clients/${this.configuration.encodeParam({ name: 'clientId', value: clientId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/familymembers/${this.configuration.encodeParam({ name: 'familyMemberId', value: familyMemberId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('delete', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: body,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getFamilyMember(
    requestParameters: GetFamilyMemberRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public getFamilyMember(
    requestParameters: GetFamilyMemberRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public getFamilyMember(
    requestParameters: GetFamilyMemberRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public getFamilyMember(
    requestParameters: GetFamilyMemberRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const familyMemberId = requestParameters?.familyMemberId;
    if (familyMemberId === null || familyMemberId === undefined) {
      throw new Error('Required parameter familyMemberId was null or undefined when calling getFamilyMember.');
    }
    const clientId = requestParameters?.clientId;
    if (clientId === null || clientId === undefined) {
      throw new Error('Required parameter clientId was null or undefined when calling getFamilyMember.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/clients/${this.configuration.encodeParam({ name: 'clientId', value: clientId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/familymembers/${this.configuration.encodeParam({ name: 'familyMemberId', value: familyMemberId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getFamilyMembers(
    requestParameters: GetFamilyMembersRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public getFamilyMembers(
    requestParameters: GetFamilyMembersRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public getFamilyMembers(
    requestParameters: GetFamilyMembersRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public getFamilyMembers(
    requestParameters: GetFamilyMembersRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const clientId = requestParameters?.clientId;
    if (clientId === null || clientId === undefined) {
      throw new Error('Required parameter clientId was null or undefined when calling getFamilyMembers.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/clients/${this.configuration.encodeParam({ name: 'clientId', value: clientId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/familymembers`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTemplate2(
    requestParameters: GetTemplate2RequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public getTemplate2(
    requestParameters: GetTemplate2RequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public getTemplate2(
    requestParameters: GetTemplate2RequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public getTemplate2(
    requestParameters: GetTemplate2RequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const clientId = requestParameters?.clientId;
    if (clientId === null || clientId === undefined) {
      throw new Error('Required parameter clientId was null or undefined when calling getTemplate2.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/clients/${this.configuration.encodeParam({ name: 'clientId', value: clientId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/familymembers/template`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateClientFamilyMembers(
    requestParameters: UpdateClientFamilyMembersRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public updateClientFamilyMembers(
    requestParameters: UpdateClientFamilyMembersRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public updateClientFamilyMembers(
    requestParameters: UpdateClientFamilyMembersRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public updateClientFamilyMembers(
    requestParameters: UpdateClientFamilyMembersRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const familyMemberId = requestParameters?.familyMemberId;
    if (familyMemberId === null || familyMemberId === undefined) {
      throw new Error(
        'Required parameter familyMemberId was null or undefined when calling updateClientFamilyMembers.'
      );
    }
    const clientId = requestParameters?.clientId;
    if (clientId === null || clientId === undefined) {
      throw new Error('Required parameter clientId was null or undefined when calling updateClientFamilyMembers.');
    }
    const body = requestParameters?.body;

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/clients/${this.configuration.encodeParam({ name: 'clientId', value: clientId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/familymembers/${this.configuration.encodeParam({ name: 'familyMemberId', value: familyMemberId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('put', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: body,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }
}
