/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
  HttpContext
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { InteropAccountData } from '../model/interopAccountData';
// @ts-ignore
import { InteropIdentifierAccountResponseData } from '../model/interopIdentifierAccountResponseData';
// @ts-ignore
import { InteropIdentifierRequestData } from '../model/interopIdentifierRequestData';
// @ts-ignore
import { InteropIdentifiersResponseData } from '../model/interopIdentifiersResponseData';
// @ts-ignore
import { InteropKycResponseData } from '../model/interopKycResponseData';
// @ts-ignore
import { InteropQuoteRequestData } from '../model/interopQuoteRequestData';
// @ts-ignore
import { InteropQuoteResponseData } from '../model/interopQuoteResponseData';
// @ts-ignore
import { InteropTransactionRequestData } from '../model/interopTransactionRequestData';
// @ts-ignore
import { InteropTransactionRequestResponseData } from '../model/interopTransactionRequestResponseData';
// @ts-ignore
import { InteropTransactionsData } from '../model/interopTransactionsData';
// @ts-ignore
import { InteropTransferRequestData } from '../model/interopTransferRequestData';
// @ts-ignore
import { InteropTransferResponseData } from '../model/interopTransferResponseData';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

export interface CreateQuoteRequestParams {
  interopQuoteRequestData: InteropQuoteRequestData;
}

export interface CreateTransactionRequestRequestParams {
  interopTransactionRequestData: InteropTransactionRequestData;
}

export interface DeleteAccountIdentifierRequestParams {
  /** idType */
  idType: 'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS';
  /** idValue */
  idValue: string;
  interopIdentifierRequestData: InteropIdentifierRequestData;
}

export interface DeleteAccountIdentifier1RequestParams {
  /** idType */
  idType: 'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS';
  /** idValue */
  idValue: string;
  /** subIdOrType */
  subIdOrType: string;
  interopIdentifierRequestData: InteropIdentifierRequestData;
}

export interface DisburseLoanRequestParams {
  /** accountId */
  accountId: string;
}

export interface GetAccountByIdentifierRequestParams {
  /** idType */
  idType: 'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS';
  /** idValue */
  idValue: string;
}

export interface GetAccountByIdentifier1RequestParams {
  /** idType */
  idType: 'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS';
  /** idValue */
  idValue: string;
  /** subIdOrType */
  subIdOrType: string;
}

export interface GetAccountDetailsRequestParams {
  /** accountId */
  accountId: string;
}

export interface GetAccountIdentifiersRequestParams {
  /** accountId */
  accountId: string;
}

export interface GetAccountTransactionsRequestParams {
  /** accountId */
  accountId: string;
  /** debit */
  debit?: boolean;
  /** credit */
  credit?: boolean;
  /** fromBookingDateTime */
  fromBookingDateTime?: string;
  /** toBookingDateTime */
  toBookingDateTime?: string;
}

export interface GetClientKycRequestParams {
  /** accountId */
  accountId: string;
}

export interface GetQuoteRequestParams {
  /** transactionCode */
  transactionCode: string;
  /** quoteCode */
  quoteCode: string;
}

export interface GetTransactionRequestRequestParams {
  /** transactionCode */
  transactionCode: string;
  /** requestCode */
  requestCode: string;
}

export interface GetTransferRequestParams {
  /** transactionCode */
  transactionCode: string;
  /** transferCode */
  transferCode: string;
}

export interface PerformTransferRequestParams {
  interopTransferRequestData: InteropTransferRequestData;
  /** action */
  action?: string;
}

export interface RegisterAccountIdentifierRequestParams {
  /** idType */
  idType: 'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS';
  /** idValue */
  idValue: string;
  interopIdentifierRequestData: InteropIdentifierRequestData;
}

export interface RegisterAccountIdentifier1RequestParams {
  /** idType */
  idType: 'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS';
  /** idValue */
  idValue: string;
  /** subIdOrType */
  subIdOrType: string;
  interopIdentifierRequestData: InteropIdentifierRequestData;
}

@Injectable({
  providedIn: 'root'
})
export class InterOperationService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration
  ) {
    super(basePath, configuration);
  }

  /**
   * Calculate Interoperation Quote
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createQuote(
    requestParameters: CreateQuoteRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropQuoteResponseData>;
  public createQuote(
    requestParameters: CreateQuoteRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropQuoteResponseData>>;
  public createQuote(
    requestParameters: CreateQuoteRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropQuoteResponseData>>;
  public createQuote(
    requestParameters: CreateQuoteRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const interopQuoteRequestData = requestParameters?.interopQuoteRequestData;
    if (interopQuoteRequestData === null || interopQuoteRequestData === undefined) {
      throw new Error('Required parameter interopQuoteRequestData was null or undefined when calling createQuote.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/quotes`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropQuoteResponseData>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: interopQuoteRequestData,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Allow Interoperation Transaction Request
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createTransactionRequest(
    requestParameters: CreateTransactionRequestRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropTransactionRequestResponseData>;
  public createTransactionRequest(
    requestParameters: CreateTransactionRequestRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropTransactionRequestResponseData>>;
  public createTransactionRequest(
    requestParameters: CreateTransactionRequestRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropTransactionRequestResponseData>>;
  public createTransactionRequest(
    requestParameters: CreateTransactionRequestRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const interopTransactionRequestData = requestParameters?.interopTransactionRequestData;
    if (interopTransactionRequestData === null || interopTransactionRequestData === undefined) {
      throw new Error(
        'Required parameter interopTransactionRequestData was null or undefined when calling createTransactionRequest.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/requests`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropTransactionRequestResponseData>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: interopTransactionRequestData,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Allow Interoperation Identifier registration
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteAccountIdentifier(
    requestParameters: DeleteAccountIdentifierRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropIdentifierAccountResponseData>;
  public deleteAccountIdentifier(
    requestParameters: DeleteAccountIdentifierRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropIdentifierAccountResponseData>>;
  public deleteAccountIdentifier(
    requestParameters: DeleteAccountIdentifierRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropIdentifierAccountResponseData>>;
  public deleteAccountIdentifier(
    requestParameters: DeleteAccountIdentifierRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const idType = requestParameters?.idType;
    if (idType === null || idType === undefined) {
      throw new Error('Required parameter idType was null or undefined when calling deleteAccountIdentifier.');
    }
    const idValue = requestParameters?.idValue;
    if (idValue === null || idValue === undefined) {
      throw new Error('Required parameter idValue was null or undefined when calling deleteAccountIdentifier.');
    }
    const interopIdentifierRequestData = requestParameters?.interopIdentifierRequestData;
    if (interopIdentifierRequestData === null || interopIdentifierRequestData === undefined) {
      throw new Error(
        'Required parameter interopIdentifierRequestData was null or undefined when calling deleteAccountIdentifier.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/parties/${this.configuration.encodeParam({ name: 'idType', value: idType, in: 'path', style: 'simple', explode: false, dataType: "'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS'", dataFormat: undefined })}/${this.configuration.encodeParam({ name: 'idValue', value: idValue, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropIdentifierAccountResponseData>('delete', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: interopIdentifierRequestData,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Allow Interoperation Identifier registration
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteAccountIdentifier1(
    requestParameters: DeleteAccountIdentifier1RequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropIdentifierAccountResponseData>;
  public deleteAccountIdentifier1(
    requestParameters: DeleteAccountIdentifier1RequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropIdentifierAccountResponseData>>;
  public deleteAccountIdentifier1(
    requestParameters: DeleteAccountIdentifier1RequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropIdentifierAccountResponseData>>;
  public deleteAccountIdentifier1(
    requestParameters: DeleteAccountIdentifier1RequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const idType = requestParameters?.idType;
    if (idType === null || idType === undefined) {
      throw new Error('Required parameter idType was null or undefined when calling deleteAccountIdentifier1.');
    }
    const idValue = requestParameters?.idValue;
    if (idValue === null || idValue === undefined) {
      throw new Error('Required parameter idValue was null or undefined when calling deleteAccountIdentifier1.');
    }
    const subIdOrType = requestParameters?.subIdOrType;
    if (subIdOrType === null || subIdOrType === undefined) {
      throw new Error('Required parameter subIdOrType was null or undefined when calling deleteAccountIdentifier1.');
    }
    const interopIdentifierRequestData = requestParameters?.interopIdentifierRequestData;
    if (interopIdentifierRequestData === null || interopIdentifierRequestData === undefined) {
      throw new Error(
        'Required parameter interopIdentifierRequestData was null or undefined when calling deleteAccountIdentifier1.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/parties/${this.configuration.encodeParam({ name: 'idType', value: idType, in: 'path', style: 'simple', explode: false, dataType: "'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS'", dataFormat: undefined })}/${this.configuration.encodeParam({ name: 'idValue', value: idValue, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/${this.configuration.encodeParam({ name: 'subIdOrType', value: subIdOrType, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropIdentifierAccountResponseData>('delete', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: interopIdentifierRequestData,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Disburse Loan by Account Id
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public disburseLoan(
    requestParameters: DisburseLoanRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public disburseLoan(
    requestParameters: DisburseLoanRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public disburseLoan(
    requestParameters: DisburseLoanRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public disburseLoan(
    requestParameters: DisburseLoanRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const accountId = requestParameters?.accountId;
    if (accountId === null || accountId === undefined) {
      throw new Error('Required parameter accountId was null or undefined when calling disburseLoan.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/transactions/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/disburse`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query Interoperation Account by secondary identifier
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAccountByIdentifier(
    requestParameters: GetAccountByIdentifierRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropIdentifierAccountResponseData>;
  public getAccountByIdentifier(
    requestParameters: GetAccountByIdentifierRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropIdentifierAccountResponseData>>;
  public getAccountByIdentifier(
    requestParameters: GetAccountByIdentifierRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropIdentifierAccountResponseData>>;
  public getAccountByIdentifier(
    requestParameters: GetAccountByIdentifierRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const idType = requestParameters?.idType;
    if (idType === null || idType === undefined) {
      throw new Error('Required parameter idType was null or undefined when calling getAccountByIdentifier.');
    }
    const idValue = requestParameters?.idValue;
    if (idValue === null || idValue === undefined) {
      throw new Error('Required parameter idValue was null or undefined when calling getAccountByIdentifier.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/parties/${this.configuration.encodeParam({ name: 'idType', value: idType, in: 'path', style: 'simple', explode: false, dataType: "'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS'", dataFormat: undefined })}/${this.configuration.encodeParam({ name: 'idValue', value: idValue, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropIdentifierAccountResponseData>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query Interoperation Account by secondary identifier
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAccountByIdentifier1(
    requestParameters: GetAccountByIdentifier1RequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropIdentifierAccountResponseData>;
  public getAccountByIdentifier1(
    requestParameters: GetAccountByIdentifier1RequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropIdentifierAccountResponseData>>;
  public getAccountByIdentifier1(
    requestParameters: GetAccountByIdentifier1RequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropIdentifierAccountResponseData>>;
  public getAccountByIdentifier1(
    requestParameters: GetAccountByIdentifier1RequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const idType = requestParameters?.idType;
    if (idType === null || idType === undefined) {
      throw new Error('Required parameter idType was null or undefined when calling getAccountByIdentifier1.');
    }
    const idValue = requestParameters?.idValue;
    if (idValue === null || idValue === undefined) {
      throw new Error('Required parameter idValue was null or undefined when calling getAccountByIdentifier1.');
    }
    const subIdOrType = requestParameters?.subIdOrType;
    if (subIdOrType === null || subIdOrType === undefined) {
      throw new Error('Required parameter subIdOrType was null or undefined when calling getAccountByIdentifier1.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/parties/${this.configuration.encodeParam({ name: 'idType', value: idType, in: 'path', style: 'simple', explode: false, dataType: "'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS'", dataFormat: undefined })}/${this.configuration.encodeParam({ name: 'idValue', value: idValue, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/${this.configuration.encodeParam({ name: 'subIdOrType', value: subIdOrType, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropIdentifierAccountResponseData>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query Interoperation Account details
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAccountDetails(
    requestParameters: GetAccountDetailsRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropAccountData>;
  public getAccountDetails(
    requestParameters: GetAccountDetailsRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropAccountData>>;
  public getAccountDetails(
    requestParameters: GetAccountDetailsRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropAccountData>>;
  public getAccountDetails(
    requestParameters: GetAccountDetailsRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const accountId = requestParameters?.accountId;
    if (accountId === null || accountId === undefined) {
      throw new Error('Required parameter accountId was null or undefined when calling getAccountDetails.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropAccountData>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query Interoperation secondary identifiers by Account Id
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAccountIdentifiers(
    requestParameters: GetAccountIdentifiersRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropIdentifiersResponseData>;
  public getAccountIdentifiers(
    requestParameters: GetAccountIdentifiersRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropIdentifiersResponseData>>;
  public getAccountIdentifiers(
    requestParameters: GetAccountIdentifiersRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropIdentifiersResponseData>>;
  public getAccountIdentifiers(
    requestParameters: GetAccountIdentifiersRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const accountId = requestParameters?.accountId;
    if (accountId === null || accountId === undefined) {
      throw new Error('Required parameter accountId was null or undefined when calling getAccountIdentifiers.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/identifiers`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropIdentifiersResponseData>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query transactions by Account Id
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAccountTransactions(
    requestParameters: GetAccountTransactionsRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropTransactionsData>;
  public getAccountTransactions(
    requestParameters: GetAccountTransactionsRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropTransactionsData>>;
  public getAccountTransactions(
    requestParameters: GetAccountTransactionsRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropTransactionsData>>;
  public getAccountTransactions(
    requestParameters: GetAccountTransactionsRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const accountId = requestParameters?.accountId;
    if (accountId === null || accountId === undefined) {
      throw new Error('Required parameter accountId was null or undefined when calling getAccountTransactions.');
    }
    const debit = requestParameters?.debit;
    const credit = requestParameters?.credit;
    const fromBookingDateTime = requestParameters?.fromBookingDateTime;
    const toBookingDateTime = requestParameters?.toBookingDateTime;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>debit, 'debit');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>credit, 'credit');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>fromBookingDateTime,
      'fromBookingDateTime'
    );
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>toBookingDateTime,
      'toBookingDateTime'
    );

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/transactions`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropTransactionsData>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query KYC by Account Id
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getClientKyc(
    requestParameters: GetClientKycRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropKycResponseData>;
  public getClientKyc(
    requestParameters: GetClientKycRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropKycResponseData>>;
  public getClientKyc(
    requestParameters: GetClientKycRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropKycResponseData>>;
  public getClientKyc(
    requestParameters: GetClientKycRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const accountId = requestParameters?.accountId;
    if (accountId === null || accountId === undefined) {
      throw new Error('Required parameter accountId was null or undefined when calling getClientKyc.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/kyc`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropKycResponseData>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query Interoperation Quote
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getQuote(
    requestParameters: GetQuoteRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropQuoteResponseData>;
  public getQuote(
    requestParameters: GetQuoteRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropQuoteResponseData>>;
  public getQuote(
    requestParameters: GetQuoteRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropQuoteResponseData>>;
  public getQuote(
    requestParameters: GetQuoteRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const transactionCode = requestParameters?.transactionCode;
    if (transactionCode === null || transactionCode === undefined) {
      throw new Error('Required parameter transactionCode was null or undefined when calling getQuote.');
    }
    const quoteCode = requestParameters?.quoteCode;
    if (quoteCode === null || quoteCode === undefined) {
      throw new Error('Required parameter quoteCode was null or undefined when calling getQuote.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/transactions/${this.configuration.encodeParam({ name: 'transactionCode', value: transactionCode, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/quotes/${this.configuration.encodeParam({ name: 'quoteCode', value: quoteCode, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropQuoteResponseData>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query Interoperation Transaction Request
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTransactionRequest(
    requestParameters: GetTransactionRequestRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropTransactionRequestResponseData>;
  public getTransactionRequest(
    requestParameters: GetTransactionRequestRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropTransactionRequestResponseData>>;
  public getTransactionRequest(
    requestParameters: GetTransactionRequestRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropTransactionRequestResponseData>>;
  public getTransactionRequest(
    requestParameters: GetTransactionRequestRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const transactionCode = requestParameters?.transactionCode;
    if (transactionCode === null || transactionCode === undefined) {
      throw new Error('Required parameter transactionCode was null or undefined when calling getTransactionRequest.');
    }
    const requestCode = requestParameters?.requestCode;
    if (requestCode === null || requestCode === undefined) {
      throw new Error('Required parameter requestCode was null or undefined when calling getTransactionRequest.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/transactions/${this.configuration.encodeParam({ name: 'transactionCode', value: transactionCode, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/requests/${this.configuration.encodeParam({ name: 'requestCode', value: requestCode, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropTransactionRequestResponseData>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query Interoperation Transfer
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTransfer(
    requestParameters: GetTransferRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropTransferResponseData>;
  public getTransfer(
    requestParameters: GetTransferRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropTransferResponseData>>;
  public getTransfer(
    requestParameters: GetTransferRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropTransferResponseData>>;
  public getTransfer(
    requestParameters: GetTransferRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const transactionCode = requestParameters?.transactionCode;
    if (transactionCode === null || transactionCode === undefined) {
      throw new Error('Required parameter transactionCode was null or undefined when calling getTransfer.');
    }
    const transferCode = requestParameters?.transferCode;
    if (transferCode === null || transferCode === undefined) {
      throw new Error('Required parameter transferCode was null or undefined when calling getTransfer.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/transactions/${this.configuration.encodeParam({ name: 'transactionCode', value: transactionCode, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/transfers/${this.configuration.encodeParam({ name: 'transferCode', value: transferCode, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropTransferResponseData>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Query Interoperation Health Request
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public health(
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: undefined; context?: HttpContext; transferCache?: boolean }
  ): Observable<any>;
  public health(
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: undefined; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<any>>;
  public health(
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: undefined; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<any>>;
  public health(
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: undefined; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/health`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<any>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Prepare Interoperation Transfer
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public performTransfer(
    requestParameters: PerformTransferRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropTransferResponseData>;
  public performTransfer(
    requestParameters: PerformTransferRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropTransferResponseData>>;
  public performTransfer(
    requestParameters: PerformTransferRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropTransferResponseData>>;
  public performTransfer(
    requestParameters: PerformTransferRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const interopTransferRequestData = requestParameters?.interopTransferRequestData;
    if (interopTransferRequestData === null || interopTransferRequestData === undefined) {
      throw new Error(
        'Required parameter interopTransferRequestData was null or undefined when calling performTransfer.'
      );
    }
    const action = requestParameters?.action;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>action, 'action');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/transfers`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropTransferResponseData>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: interopTransferRequestData,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Interoperation Identifier registration
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public registerAccountIdentifier(
    requestParameters: RegisterAccountIdentifierRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropIdentifierAccountResponseData>;
  public registerAccountIdentifier(
    requestParameters: RegisterAccountIdentifierRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropIdentifierAccountResponseData>>;
  public registerAccountIdentifier(
    requestParameters: RegisterAccountIdentifierRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropIdentifierAccountResponseData>>;
  public registerAccountIdentifier(
    requestParameters: RegisterAccountIdentifierRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const idType = requestParameters?.idType;
    if (idType === null || idType === undefined) {
      throw new Error('Required parameter idType was null or undefined when calling registerAccountIdentifier.');
    }
    const idValue = requestParameters?.idValue;
    if (idValue === null || idValue === undefined) {
      throw new Error('Required parameter idValue was null or undefined when calling registerAccountIdentifier.');
    }
    const interopIdentifierRequestData = requestParameters?.interopIdentifierRequestData;
    if (interopIdentifierRequestData === null || interopIdentifierRequestData === undefined) {
      throw new Error(
        'Required parameter interopIdentifierRequestData was null or undefined when calling registerAccountIdentifier.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/parties/${this.configuration.encodeParam({ name: 'idType', value: idType, in: 'path', style: 'simple', explode: false, dataType: "'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS'", dataFormat: undefined })}/${this.configuration.encodeParam({ name: 'idValue', value: idValue, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropIdentifierAccountResponseData>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: interopIdentifierRequestData,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Interoperation Identifier registration
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public registerAccountIdentifier1(
    requestParameters: RegisterAccountIdentifier1RequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<InteropIdentifierAccountResponseData>;
  public registerAccountIdentifier1(
    requestParameters: RegisterAccountIdentifier1RequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<InteropIdentifierAccountResponseData>>;
  public registerAccountIdentifier1(
    requestParameters: RegisterAccountIdentifier1RequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<InteropIdentifierAccountResponseData>>;
  public registerAccountIdentifier1(
    requestParameters: RegisterAccountIdentifier1RequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const idType = requestParameters?.idType;
    if (idType === null || idType === undefined) {
      throw new Error('Required parameter idType was null or undefined when calling registerAccountIdentifier1.');
    }
    const idValue = requestParameters?.idValue;
    if (idValue === null || idValue === undefined) {
      throw new Error('Required parameter idValue was null or undefined when calling registerAccountIdentifier1.');
    }
    const subIdOrType = requestParameters?.subIdOrType;
    if (subIdOrType === null || subIdOrType === undefined) {
      throw new Error('Required parameter subIdOrType was null or undefined when calling registerAccountIdentifier1.');
    }
    const interopIdentifierRequestData = requestParameters?.interopIdentifierRequestData;
    if (interopIdentifierRequestData === null || interopIdentifierRequestData === undefined) {
      throw new Error(
        'Required parameter interopIdentifierRequestData was null or undefined when calling registerAccountIdentifier1.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/interoperation/parties/${this.configuration.encodeParam({ name: 'idType', value: idType, in: 'path', style: 'simple', explode: false, dataType: "'MSISDN' | 'EMAIL' | 'PERSONAL_ID' | 'BUSINESS' | 'DEVICE' | 'ACCOUNT_ID' | 'IBAN' | 'ALIAS'", dataFormat: undefined })}/${this.configuration.encodeParam({ name: 'idValue', value: idValue, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/${this.configuration.encodeParam({ name: 'subIdOrType', value: subIdOrType, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<InteropIdentifierAccountResponseData>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: interopIdentifierRequestData,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }
}
