/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
  HttpContext
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { DeleteLoansLoanIdResponse } from '../model/deleteLoansLoanIdResponse';
// @ts-ignore
import { GetLoansLoanIdResponse } from '../model/getLoansLoanIdResponse';
// @ts-ignore
import { GetLoansResponse } from '../model/getLoansResponse';
// @ts-ignore
import { GetLoansTemplateResponse } from '../model/getLoansTemplateResponse';
// @ts-ignore
import { PostLoansLoanIdRequest } from '../model/postLoansLoanIdRequest';
// @ts-ignore
import { PostLoansLoanIdResponse } from '../model/postLoansLoanIdResponse';
// @ts-ignore
import { PostLoansRequest } from '../model/postLoansRequest';
// @ts-ignore
import { PostLoansResponse } from '../model/postLoansResponse';
// @ts-ignore
import { PutLoansLoanIdRequest } from '../model/putLoansLoanIdRequest';
// @ts-ignore
import { PutLoansLoanIdResponse } from '../model/putLoansLoanIdResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

export interface CalculateLoanScheduleOrSubmitLoanApplicationRequestParams {
  postLoansRequest: PostLoansRequest;
  /** command */
  command?: string;
}

export interface DeleteLoanApplicationRequestParams {
  /** loanId */
  loanId: number;
}

export interface GetGlimRepaymentTemplateRequestParams {
  glimId: number;
}

export interface GetLoanRepaymentTemplateRequestParams {
  officeId?: number;
  dateFormat?: string;
}

export interface GetLoansTemplateRequestParams {
  officeId?: number;
  staffId?: number;
  dateFormat?: string;
}

export interface GlimStateTransitionsRequestParams {
  glimId: number;
  postLoansLoanIdRequest: PostLoansLoanIdRequest;
  command?: string;
}

export interface ModifyLoanApplicationRequestParams {
  /** loanId */
  loanId: number;
  putLoansLoanIdRequest: PutLoansLoanIdRequest;
}

export interface PostLoanRepaymentTemplateRequestParams {
  uploadedInputStream?: Blob;
  locale?: string;
  dateFormat?: string;
}

export interface PostLoanTemplateRequestParams {
  uploadedInputStream?: Blob;
  locale?: string;
  dateFormat?: string;
}

export interface RetrieveAll27RequestParams {
  /** sqlSearch */
  sqlSearch?: string;
  /** externalId */
  externalId?: string;
  /** offset */
  offset?: number;
  /** limit */
  limit?: number;
  /** orderBy */
  orderBy?: string;
  /** sortOrder */
  sortOrder?: string;
  /** accountNo */
  accountNo?: string;
}

export interface RetrieveApprovalTemplateRequestParams {
  /** loanId */
  loanId: number;
  /** templateType */
  templateType?: string;
}

export interface RetrieveLoanRequestParams {
  /** loanId */
  loanId: number;
  /** staffInSelectedOfficeOnly */
  staffInSelectedOfficeOnly?: boolean;
}

export interface StateTransitionsRequestParams {
  /** loanId */
  loanId: number;
  postLoansLoanIdRequest: PostLoansLoanIdRequest;
  /** command */
  command?: string;
}

export interface Template10RequestParams {
  /** clientId */
  clientId?: number;
  /** groupId */
  groupId?: number;
  /** productId */
  productId?: number;
  /** templateType */
  templateType?: string;
  /** staffInSelectedOfficeOnly */
  staffInSelectedOfficeOnly?: boolean;
  /** activeOnly */
  activeOnly?: boolean;
}

@Injectable({
  providedIn: 'root'
})
export class LoansService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration
  ) {
    super(basePath, configuration);
  }

  /**
   * Calculate loan repayment schedule | Submit a new Loan Application
   * It calculates the loan repayment Schedule Submits a new loan application Mandatory Fields: clientId, productId, principal, loanTermFrequency, loanTermFrequencyType, loanType, numberOfRepayments, repaymentEvery, repaymentFrequencyType, interestRatePerPeriod, amortizationType, interestType, interestCalculationPeriodType, transactionProcessingStrategyId, expectedDisbursementDate, submittedOnDate, loanType Optional Fields: graceOnPrincipalPayment, graceOnInterestPayment, graceOnInterestCharged, linkAccountId, allowPartialPeriodInterestCalcualtion, fixedEmiAmount, maxOutstandingLoanBalance, disbursementData, graceOnArrearsAgeing, createStandingInstructionAtDisbursement (requires linkedAccountId if set to true) Additional Mandatory Fields if interest recalculation is enabled for product and Rest frequency not same as repayment period: recalculationRestFrequencyDate Additional Mandatory Fields if interest recalculation with interest/fee compounding is enabled for product and compounding frequency not same as repayment period: recalculationCompoundingFrequencyDate Additional Mandatory Field if Entity-Datatable Check is enabled for the entity of type loan: datatables
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public calculateLoanScheduleOrSubmitLoanApplication(
    requestParameters: CalculateLoanScheduleOrSubmitLoanApplicationRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<PostLoansResponse>;
  public calculateLoanScheduleOrSubmitLoanApplication(
    requestParameters: CalculateLoanScheduleOrSubmitLoanApplicationRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<PostLoansResponse>>;
  public calculateLoanScheduleOrSubmitLoanApplication(
    requestParameters: CalculateLoanScheduleOrSubmitLoanApplicationRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<PostLoansResponse>>;
  public calculateLoanScheduleOrSubmitLoanApplication(
    requestParameters: CalculateLoanScheduleOrSubmitLoanApplicationRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const postLoansRequest = requestParameters?.postLoansRequest;
    if (postLoansRequest === null || postLoansRequest === undefined) {
      throw new Error(
        'Required parameter postLoansRequest was null or undefined when calling calculateLoanScheduleOrSubmitLoanApplication.'
      );
    }
    const command = requestParameters?.command;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>command, 'command');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<PostLoansResponse>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: postLoansRequest,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Delete a Loan Application
   * Note: Only loans in \&quot;Submitted and awaiting approval\&quot; status can be deleted.
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteLoanApplication(
    requestParameters: DeleteLoanApplicationRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<DeleteLoansLoanIdResponse>;
  public deleteLoanApplication(
    requestParameters: DeleteLoanApplicationRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<DeleteLoansLoanIdResponse>>;
  public deleteLoanApplication(
    requestParameters: DeleteLoanApplicationRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<DeleteLoansLoanIdResponse>>;
  public deleteLoanApplication(
    requestParameters: DeleteLoanApplicationRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const loanId = requestParameters?.loanId;
    if (loanId === null || loanId === undefined) {
      throw new Error('Required parameter loanId was null or undefined when calling deleteLoanApplication.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/${this.configuration.encodeParam({ name: 'loanId', value: loanId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<DeleteLoansLoanIdResponse>('delete', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getGlimRepaymentTemplate(
    requestParameters: GetGlimRepaymentTemplateRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public getGlimRepaymentTemplate(
    requestParameters: GetGlimRepaymentTemplateRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public getGlimRepaymentTemplate(
    requestParameters: GetGlimRepaymentTemplateRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public getGlimRepaymentTemplate(
    requestParameters: GetGlimRepaymentTemplateRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const glimId = requestParameters?.glimId;
    if (glimId === null || glimId === undefined) {
      throw new Error('Required parameter glimId was null or undefined when calling getGlimRepaymentTemplate.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/glimAccount/${this.configuration.encodeParam({ name: 'glimId', value: glimId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getLoanRepaymentTemplate(
    requestParameters?: GetLoanRepaymentTemplateRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/vnd.ms-excel'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any>;
  public getLoanRepaymentTemplate(
    requestParameters?: GetLoanRepaymentTemplateRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/vnd.ms-excel'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<any>>;
  public getLoanRepaymentTemplate(
    requestParameters?: GetLoanRepaymentTemplateRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/vnd.ms-excel'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<any>>;
  public getLoanRepaymentTemplate(
    requestParameters?: GetLoanRepaymentTemplateRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/vnd.ms-excel'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const officeId = requestParameters?.officeId;
    const dateFormat = requestParameters?.dateFormat;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>officeId, 'officeId');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>dateFormat, 'dateFormat');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/vnd.ms-excel'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/repayments/downloadtemplate`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<any>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getLoansTemplate(
    requestParameters?: GetLoansTemplateRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/vnd.ms-excel'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any>;
  public getLoansTemplate(
    requestParameters?: GetLoansTemplateRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/vnd.ms-excel'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<any>>;
  public getLoansTemplate(
    requestParameters?: GetLoansTemplateRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/vnd.ms-excel'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<any>>;
  public getLoansTemplate(
    requestParameters?: GetLoansTemplateRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/vnd.ms-excel'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const officeId = requestParameters?.officeId;
    const staffId = requestParameters?.staffId;
    const dateFormat = requestParameters?.dateFormat;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>officeId, 'officeId');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>staffId, 'staffId');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>dateFormat, 'dateFormat');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/vnd.ms-excel'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/downloadtemplate`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<any>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Approve GLIM Application | Undo GLIM Application Approval | Reject GLIM Application | Disburse Loan Disburse Loan To Savings Account | Undo Loan Disbursal
   * Approve GLIM Application: Mandatory Fields: approvedOnDate Optional Fields: approvedLoanAmount and expectedDisbursementDate Approves the GLIM application  Undo GLIM Application Approval: Undoes the GLIM Application Approval  Reject GLIM Application: Mandatory Fields: rejectedOnDate Allows you to reject the GLIM application  Disburse Loan: Mandatory Fields: actualDisbursementDate Optional Fields: transactionAmount and fixedEmiAmount Disburses the Loan  Disburse Loan To Savings Account: Mandatory Fields: actualDisbursementDate Optional Fields: transactionAmount and fixedEmiAmount Disburses the loan to Saving Account  Undo Loan Disbursal: Undoes the Loan Disbursal
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public glimStateTransitions(
    requestParameters: GlimStateTransitionsRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<PostLoansLoanIdResponse>;
  public glimStateTransitions(
    requestParameters: GlimStateTransitionsRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<PostLoansLoanIdResponse>>;
  public glimStateTransitions(
    requestParameters: GlimStateTransitionsRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<PostLoansLoanIdResponse>>;
  public glimStateTransitions(
    requestParameters: GlimStateTransitionsRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const glimId = requestParameters?.glimId;
    if (glimId === null || glimId === undefined) {
      throw new Error('Required parameter glimId was null or undefined when calling glimStateTransitions.');
    }
    const postLoansLoanIdRequest = requestParameters?.postLoansLoanIdRequest;
    if (postLoansLoanIdRequest === null || postLoansLoanIdRequest === undefined) {
      throw new Error(
        'Required parameter postLoansLoanIdRequest was null or undefined when calling glimStateTransitions.'
      );
    }
    const command = requestParameters?.command;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>command, 'command');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/glimAccount/${this.configuration.encodeParam({ name: 'glimId', value: glimId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<PostLoansLoanIdResponse>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: postLoansLoanIdRequest,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Modify a loan application
   * Loan application can only be modified when in \&#39;Submitted and pending approval\&#39; state. Once the application is approved, the details cannot be changed using this method.
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public modifyLoanApplication(
    requestParameters: ModifyLoanApplicationRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<PutLoansLoanIdResponse>;
  public modifyLoanApplication(
    requestParameters: ModifyLoanApplicationRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<PutLoansLoanIdResponse>>;
  public modifyLoanApplication(
    requestParameters: ModifyLoanApplicationRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<PutLoansLoanIdResponse>>;
  public modifyLoanApplication(
    requestParameters: ModifyLoanApplicationRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const loanId = requestParameters?.loanId;
    if (loanId === null || loanId === undefined) {
      throw new Error('Required parameter loanId was null or undefined when calling modifyLoanApplication.');
    }
    const putLoansLoanIdRequest = requestParameters?.putLoansLoanIdRequest;
    if (putLoansLoanIdRequest === null || putLoansLoanIdRequest === undefined) {
      throw new Error(
        'Required parameter putLoansLoanIdRequest was null or undefined when calling modifyLoanApplication.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/${this.configuration.encodeParam({ name: 'loanId', value: loanId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<PutLoansLoanIdResponse>('put', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: putLoansLoanIdRequest,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postLoanRepaymentTemplate(
    requestParameters?: PostLoanRepaymentTemplateRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public postLoanRepaymentTemplate(
    requestParameters?: PostLoanRepaymentTemplateRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public postLoanRepaymentTemplate(
    requestParameters?: PostLoanRepaymentTemplateRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public postLoanRepaymentTemplate(
    requestParameters?: PostLoanRepaymentTemplateRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const uploadedInputStream = requestParameters?.uploadedInputStream;
    const locale = requestParameters?.locale;
    const dateFormat = requestParameters?.dateFormat;

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        '*/*'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'multipart/form-data'
    ];

    const canConsumeForm = this.canConsumeForm(consumes);

    let localVarFormParams: { append(param: string, value: any): any };
    let localVarUseForm = false;
    let localVarConvertFormParamsToString = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
    localVarUseForm = canConsumeForm;
    if (localVarUseForm) {
      localVarFormParams = new FormData();
    } else {
      localVarFormParams = new HttpParams({ encoder: this.encoder });
    }

    if (uploadedInputStream !== undefined) {
      localVarFormParams =
        (localVarFormParams.append('uploadedInputStream', <any>uploadedInputStream) as any) || localVarFormParams;
    }
    if (locale !== undefined) {
      localVarFormParams = (localVarFormParams.append('locale', <any>locale) as any) || localVarFormParams;
    }
    if (dateFormat !== undefined) {
      localVarFormParams = (localVarFormParams.append('dateFormat', <any>dateFormat) as any) || localVarFormParams;
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/repayments/uploadtemplate`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postLoanTemplate(
    requestParameters?: PostLoanTemplateRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public postLoanTemplate(
    requestParameters?: PostLoanTemplateRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public postLoanTemplate(
    requestParameters?: PostLoanTemplateRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public postLoanTemplate(
    requestParameters?: PostLoanTemplateRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const uploadedInputStream = requestParameters?.uploadedInputStream;
    const locale = requestParameters?.locale;
    const dateFormat = requestParameters?.dateFormat;

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        '*/*'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'multipart/form-data'
    ];

    const canConsumeForm = this.canConsumeForm(consumes);

    let localVarFormParams: { append(param: string, value: any): any };
    let localVarUseForm = false;
    let localVarConvertFormParamsToString = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
    localVarUseForm = canConsumeForm;
    if (localVarUseForm) {
      localVarFormParams = new FormData();
    } else {
      localVarFormParams = new HttpParams({ encoder: this.encoder });
    }

    if (uploadedInputStream !== undefined) {
      localVarFormParams =
        (localVarFormParams.append('uploadedInputStream', <any>uploadedInputStream) as any) || localVarFormParams;
    }
    if (locale !== undefined) {
      localVarFormParams = (localVarFormParams.append('locale', <any>locale) as any) || localVarFormParams;
    }
    if (dateFormat !== undefined) {
      localVarFormParams = (localVarFormParams.append('dateFormat', <any>dateFormat) as any) || localVarFormParams;
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/uploadtemplate`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * List Loans
   * The list capability of loans can support pagination and sorting. Example Requests:  loans  loans?fields&#x3D;accountNo  loans?offset&#x3D;10&amp;limit&#x3D;50  loans?orderBy&#x3D;accountNo&amp;sortOrder&#x3D;DESC
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public retrieveAll27(
    requestParameters?: RetrieveAll27RequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<GetLoansResponse>;
  public retrieveAll27(
    requestParameters?: RetrieveAll27RequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<GetLoansResponse>>;
  public retrieveAll27(
    requestParameters?: RetrieveAll27RequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<GetLoansResponse>>;
  public retrieveAll27(
    requestParameters?: RetrieveAll27RequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const sqlSearch = requestParameters?.sqlSearch;
    const externalId = requestParameters?.externalId;
    const offset = requestParameters?.offset;
    const limit = requestParameters?.limit;
    const orderBy = requestParameters?.orderBy;
    const sortOrder = requestParameters?.sortOrder;
    const accountNo = requestParameters?.accountNo;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>sqlSearch, 'sqlSearch');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>externalId, 'externalId');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>offset, 'offset');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>limit, 'limit');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>orderBy, 'orderBy');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>sortOrder, 'sortOrder');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>accountNo, 'accountNo');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<GetLoansResponse>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public retrieveApprovalTemplate(
    requestParameters: RetrieveApprovalTemplateRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<string>;
  public retrieveApprovalTemplate(
    requestParameters: RetrieveApprovalTemplateRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<string>>;
  public retrieveApprovalTemplate(
    requestParameters: RetrieveApprovalTemplateRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<string>>;
  public retrieveApprovalTemplate(
    requestParameters: RetrieveApprovalTemplateRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const loanId = requestParameters?.loanId;
    if (loanId === null || loanId === undefined) {
      throw new Error('Required parameter loanId was null or undefined when calling retrieveApprovalTemplate.');
    }
    const templateType = requestParameters?.templateType;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>templateType, 'templateType');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/${this.configuration.encodeParam({ name: 'loanId', value: loanId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/template`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Retrieve a Loan
   * Note: template&#x3D;true parameter doesn\&#39;t apply to this resource.Example Requests:  loans/1   loans/1?fields&#x3D;id,principal,annualInterestRate   loans/1?associations&#x3D;all  loans/1?associations&#x3D;all&amp;exclude&#x3D;guarantors   loans/1?fields&#x3D;id,principal,annualInterestRate&amp;associations&#x3D;repaymentSchedule,transactions
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public retrieveLoan(
    requestParameters: RetrieveLoanRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<GetLoansLoanIdResponse>;
  public retrieveLoan(
    requestParameters: RetrieveLoanRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<GetLoansLoanIdResponse>>;
  public retrieveLoan(
    requestParameters: RetrieveLoanRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<GetLoansLoanIdResponse>>;
  public retrieveLoan(
    requestParameters: RetrieveLoanRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const loanId = requestParameters?.loanId;
    if (loanId === null || loanId === undefined) {
      throw new Error('Required parameter loanId was null or undefined when calling retrieveLoan.');
    }
    const staffInSelectedOfficeOnly = requestParameters?.staffInSelectedOfficeOnly;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>staffInSelectedOfficeOnly,
      'staffInSelectedOfficeOnly'
    );

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/${this.configuration.encodeParam({ name: 'loanId', value: loanId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<GetLoansLoanIdResponse>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Approve Loan Application | Recover Loan Guarantee | Undo Loan Application Approval | Assign a Loan Officer | Unassign a Loan Officer | Reject Loan Application | Applicant Withdraws from Loan Application | Disburse Loan Disburse Loan To Savings Account | Undo Loan Disbursal
   * Approve Loan Application: Mandatory Fields: approvedOnDate Optional Fields: approvedLoanAmount and expectedDisbursementDate Approves the loan application  Recover Loan Guarantee: Recovers the loan guarantee  Undo Loan Application Approval: Undoes the Loan Application Approval  Assign a Loan Officer: Allows you to assign Loan Officer for existing Loan.  Unassign a Loan Officer: Allows you to unassign the Loan Officer.  Reject Loan Application: Mandatory Fields: rejectedOnDate Allows you to reject the loan application  Applicant Withdraws from Loan Application: Mandatory Fields: withdrawnOnDate Allows the applicant to withdraw the loan application  Disburse Loan: Mandatory Fields: actualDisbursementDate Optional Fields: transactionAmount and fixedEmiAmount Disburses the Loan  Disburse Loan To Savings Account: Mandatory Fields: actualDisbursementDate Optional Fields: transactionAmount and fixedEmiAmount Disburses the loan to Saving Account  Undo Loan Disbursal: Undoes the Loan Disbursal Showing request and response for Assign a Loan Officer
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public stateTransitions(
    requestParameters: StateTransitionsRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<PostLoansLoanIdResponse>;
  public stateTransitions(
    requestParameters: StateTransitionsRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<PostLoansLoanIdResponse>>;
  public stateTransitions(
    requestParameters: StateTransitionsRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<PostLoansLoanIdResponse>>;
  public stateTransitions(
    requestParameters: StateTransitionsRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const loanId = requestParameters?.loanId;
    if (loanId === null || loanId === undefined) {
      throw new Error('Required parameter loanId was null or undefined when calling stateTransitions.');
    }
    const postLoansLoanIdRequest = requestParameters?.postLoansLoanIdRequest;
    if (postLoansLoanIdRequest === null || postLoansLoanIdRequest === undefined) {
      throw new Error('Required parameter postLoansLoanIdRequest was null or undefined when calling stateTransitions.');
    }
    const command = requestParameters?.command;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>command, 'command');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/${this.configuration.encodeParam({ name: 'loanId', value: loanId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<PostLoansLoanIdResponse>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: postLoansLoanIdRequest,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Retrieve Loan Details Template
   * This is a convenience resource. It can be useful when building maintenance user interface screens for client applications. The template data returned consists of any or all of:  Field Defaults Allowed description Lists Example Requests:  loans/template?templateType&#x3D;individual&amp;clientId&#x3D;1   loans/template?templateType&#x3D;individual&amp;clientId&#x3D;1&amp;productId&#x3D;1
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public template10(
    requestParameters?: Template10RequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<GetLoansTemplateResponse>;
  public template10(
    requestParameters?: Template10RequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<GetLoansTemplateResponse>>;
  public template10(
    requestParameters?: Template10RequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<GetLoansTemplateResponse>>;
  public template10(
    requestParameters?: Template10RequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const clientId = requestParameters?.clientId;
    const groupId = requestParameters?.groupId;
    const productId = requestParameters?.productId;
    const templateType = requestParameters?.templateType;
    const staffInSelectedOfficeOnly = requestParameters?.staffInSelectedOfficeOnly;
    const activeOnly = requestParameters?.activeOnly;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>clientId, 'clientId');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>groupId, 'groupId');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>productId, 'productId');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>templateType, 'templateType');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>staffInSelectedOfficeOnly,
      'staffInSelectedOfficeOnly'
    );
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>activeOnly, 'activeOnly');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/template`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<GetLoansTemplateResponse>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }
}
