/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
  HttpContext
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { DeletePostDatedCheck } from '../model/deletePostDatedCheck';
// @ts-ignore
import { GetPostDatedChecks } from '../model/getPostDatedChecks';
// @ts-ignore
import { UpdatePostDatedCheckRequest } from '../model/updatePostDatedCheckRequest';
// @ts-ignore
import { UpdatePostDatedCheckResponse } from '../model/updatePostDatedCheckResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

export interface DeletePostDatedCheckRequestParams {
  /** postDatedCheckId */
  postDatedCheckId: number;
  /** loanId */
  loanId: number;
}

export interface GetPostDatedCheckRequestParams {
  /** installmentId */
  installmentId: number;
  /** loanId */
  loanId: number;
}

export interface GetPostDatedChecksRequestParams {
  /** loanId */
  loanId: number;
}

export interface UpdatePostDatedChecksRequestParams {
  /** postDatedCheckId */
  postDatedCheckId: number;
  /** loanId */
  loanId: number;
  updatePostDatedCheckRequest: UpdatePostDatedCheckRequest;
  /** editType */
  editType?: string;
}

@Injectable({
  providedIn: 'root'
})
export class RepaymentWithPostDatedChecksService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration
  ) {
    super(basePath, configuration);
  }

  /**
   * Delete Post Dated Check
   * Delete Post Dated Check
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deletePostDatedCheck(
    requestParameters: DeletePostDatedCheckRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<Array<DeletePostDatedCheck>>;
  public deletePostDatedCheck(
    requestParameters: DeletePostDatedCheckRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<Array<DeletePostDatedCheck>>>;
  public deletePostDatedCheck(
    requestParameters: DeletePostDatedCheckRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<Array<DeletePostDatedCheck>>>;
  public deletePostDatedCheck(
    requestParameters: DeletePostDatedCheckRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const postDatedCheckId = requestParameters?.postDatedCheckId;
    if (postDatedCheckId === null || postDatedCheckId === undefined) {
      throw new Error('Required parameter postDatedCheckId was null or undefined when calling deletePostDatedCheck.');
    }
    const loanId = requestParameters?.loanId;
    if (loanId === null || loanId === undefined) {
      throw new Error('Required parameter loanId was null or undefined when calling deletePostDatedCheck.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/${this.configuration.encodeParam({ name: 'loanId', value: loanId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/postdatedchecks/${this.configuration.encodeParam({ name: 'postDatedCheckId', value: postDatedCheckId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<Array<DeletePostDatedCheck>>('delete', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Get Post Dated Check
   * Get Post Dated Check
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getPostDatedCheck(
    requestParameters: GetPostDatedCheckRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<Array<GetPostDatedChecks>>;
  public getPostDatedCheck(
    requestParameters: GetPostDatedCheckRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<Array<GetPostDatedChecks>>>;
  public getPostDatedCheck(
    requestParameters: GetPostDatedCheckRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<Array<GetPostDatedChecks>>>;
  public getPostDatedCheck(
    requestParameters: GetPostDatedCheckRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const installmentId = requestParameters?.installmentId;
    if (installmentId === null || installmentId === undefined) {
      throw new Error('Required parameter installmentId was null or undefined when calling getPostDatedCheck.');
    }
    const loanId = requestParameters?.loanId;
    if (loanId === null || loanId === undefined) {
      throw new Error('Required parameter loanId was null or undefined when calling getPostDatedCheck.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/${this.configuration.encodeParam({ name: 'loanId', value: loanId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/postdatedchecks/${this.configuration.encodeParam({ name: 'installmentId', value: installmentId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int32' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<Array<GetPostDatedChecks>>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Get All Post Dated Checks
   * Get All Post dated Checks
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getPostDatedChecks(
    requestParameters: GetPostDatedChecksRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<Array<GetPostDatedChecks>>;
  public getPostDatedChecks(
    requestParameters: GetPostDatedChecksRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<Array<GetPostDatedChecks>>>;
  public getPostDatedChecks(
    requestParameters: GetPostDatedChecksRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<Array<GetPostDatedChecks>>>;
  public getPostDatedChecks(
    requestParameters: GetPostDatedChecksRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const loanId = requestParameters?.loanId;
    if (loanId === null || loanId === undefined) {
      throw new Error('Required parameter loanId was null or undefined when calling getPostDatedChecks.');
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/${this.configuration.encodeParam({ name: 'loanId', value: loanId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/postdatedchecks`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<Array<GetPostDatedChecks>>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }

  /**
   * Update Post Dated Check, Bounced Check
   * Update Post Dated Check, Bounced Check
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updatePostDatedChecks(
    requestParameters: UpdatePostDatedChecksRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<Array<UpdatePostDatedCheckResponse>>;
  public updatePostDatedChecks(
    requestParameters: UpdatePostDatedChecksRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<Array<UpdatePostDatedCheckResponse>>>;
  public updatePostDatedChecks(
    requestParameters: UpdatePostDatedChecksRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<Array<UpdatePostDatedCheckResponse>>>;
  public updatePostDatedChecks(
    requestParameters: UpdatePostDatedChecksRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    const postDatedCheckId = requestParameters?.postDatedCheckId;
    if (postDatedCheckId === null || postDatedCheckId === undefined) {
      throw new Error('Required parameter postDatedCheckId was null or undefined when calling updatePostDatedChecks.');
    }
    const loanId = requestParameters?.loanId;
    if (loanId === null || loanId === undefined) {
      throw new Error('Required parameter loanId was null or undefined when calling updatePostDatedChecks.');
    }
    const updatePostDatedCheckRequest = requestParameters?.updatePostDatedCheckRequest;
    if (updatePostDatedCheckRequest === null || updatePostDatedCheckRequest === undefined) {
      throw new Error(
        'Required parameter updatePostDatedCheckRequest was null or undefined when calling updatePostDatedChecks.'
      );
    }
    const editType = requestParameters?.editType;

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>editType, 'editType');

    let localVarHeaders = this.defaultHeaders;

    // authentication (basicAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'basicAuth',
      'Authorization',
      localVarHeaders,
      'Basic '
    );

    // authentication (tenantid) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'tenantid',
      'fineract-platform-tenantid',
      localVarHeaders
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/json'
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/loans/${this.configuration.encodeParam({ name: 'loanId', value: loanId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}/postdatedchecks/${this.configuration.encodeParam({ name: 'postDatedCheckId', value: postDatedCheckId, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: 'int64' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<Array<UpdatePostDatedCheckResponse>>('put', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: updatePostDatedCheckRequest,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress
    });
  }
}
