export * from './accountNumberFormat.service';
import { AccountNumberFormatService } from './accountNumberFormat.service';
export * from './accountTransfers.service';
import { AccountTransfersService } from './accountTransfers.service';
export * from './accountingClosure.service';
import { AccountingClosureService } from './accountingClosure.service';
export * from './accountingRules.service';
import { AccountingRulesService } from './accountingRules.service';
export * from './adhocQueryApi.service';
import { AdhocQueryApiService } from './adhocQueryApi.service';
export * from './audits.service';
import { AuditsService } from './audits.service';
export * from './authenticationHTTPBasic.service';
import { AuthenticationHTTPBasicService } from './authenticationHTTPBasic.service';
export * from './batchAPI.service';
import { BatchAPIService } from './batchAPI.service';
export * from './bulkImport.service';
import { BulkImportService } from './bulkImport.service';
export * from './bulkLoans.service';
import { BulkLoansService } from './bulkLoans.service';
export * from './businessDateManagement.service';
import { BusinessDateManagementService } from './businessDateManagement.service';
export * from './businessStepConfiguration.service';
import { BusinessStepConfigurationService } from './businessStepConfiguration.service';
export * from './cache.service';
import { CacheService } from './cache.service';
export * from './calendar.service';
import { CalendarService } from './calendar.service';
export * from './cashierJournals.service';
import { CashierJournalsService } from './cashierJournals.service';
export * from './cashiers.service';
import { CashiersService } from './cashiers.service';
export * from './centers.service';
import { CentersService } from './centers.service';
export * from './charges.service';
import { ChargesService } from './charges.service';
export * from './client.service';
import { ClientService } from './client.service';
export * from './clientCharges.service';
import { ClientChargesService } from './clientCharges.service';
export * from './clientCollateralManagement.service';
import { ClientCollateralManagementService } from './clientCollateralManagement.service';
export * from './clientFamilyMember.service';
import { ClientFamilyMemberService } from './clientFamilyMember.service';
export * from './clientIdentifier.service';
import { ClientIdentifierService } from './clientIdentifier.service';
export * from './clientSearchV2.service';
import { ClientSearchV2Service } from './clientSearchV2.service';
export * from './clientTransaction.service';
import { ClientTransactionService } from './clientTransaction.service';
export * from './clientsAddress.service';
import { ClientsAddressService } from './clientsAddress.service';
export * from './codeValues.service';
import { CodeValuesService } from './codeValues.service';
export * from './codes.service';
import { CodesService } from './codes.service';
export * from './collateralManagement.service';
import { CollateralManagementService } from './collateralManagement.service';
export * from './collectionSheet.service';
import { CollectionSheetService } from './collectionSheet.service';
export * from './creditBureauConfiguration.service';
import { CreditBureauConfigurationService } from './creditBureauConfiguration.service';
export * from './currency.service';
import { CurrencyService } from './currency.service';
export * from './dataTables.service';
import { DataTablesService } from './dataTables.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './delinquencyRangeAndBucketsManagement.service';
import { DelinquencyRangeAndBucketsManagementService } from './delinquencyRangeAndBucketsManagement.service';
export * from './depositAccountOnHoldFundTransactions.service';
import { DepositAccountOnHoldFundTransactionsService } from './depositAccountOnHoldFundTransactions.service';
export * from './deviceRegistration.service';
import { DeviceRegistrationService } from './deviceRegistration.service';
export * from './documents.service';
import { DocumentsService } from './documents.service';
export * from './entityDataTable.service';
import { EntityDataTableService } from './entityDataTable.service';
export * from './entityFieldConfiguration.service';
import { EntityFieldConfigurationService } from './entityFieldConfiguration.service';
export * from './externalAssetOwners.service';
import { ExternalAssetOwnersService } from './externalAssetOwners.service';
export * from './externalEventConfiguration.service';
import { ExternalEventConfigurationService } from './externalEventConfiguration.service';
export * from './externalServices.service';
import { ExternalServicesService } from './externalServices.service';
export * from './fetchAuthenticatedUserDetails.service';
import { FetchAuthenticatedUserDetailsService } from './fetchAuthenticatedUserDetails.service';
export * from './fineractEntity.service';
import { FineractEntityService } from './fineractEntity.service';
export * from './fixedDepositAccount.service';
import { FixedDepositAccountService } from './fixedDepositAccount.service';
export * from './fixedDepositAccountTransactions.service';
import { FixedDepositAccountTransactionsService } from './fixedDepositAccountTransactions.service';
export * from './fixedDepositProduct.service';
import { FixedDepositProductService } from './fixedDepositProduct.service';
export * from './floatingRates.service';
import { FloatingRatesService } from './floatingRates.service';
export * from './funds.service';
import { FundsService } from './funds.service';
export * from './generalLedgerAccount.service';
import { GeneralLedgerAccountService } from './generalLedgerAccount.service';
export * from './globalConfiguration.service';
import { GlobalConfigurationService } from './globalConfiguration.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './groupsLevel.service';
import { GroupsLevelService } from './groupsLevel.service';
export * from './guarantors.service';
import { GuarantorsService } from './guarantors.service';
export * from './holidays.service';
import { HolidaysService } from './holidays.service';
export * from './hooks.service';
import { HooksService } from './hooks.service';
export * from './inlineJob.service';
import { InlineJobService } from './inlineJob.service';
export * from './instanceMode.service';
import { InstanceModeService } from './instanceMode.service';
export * from './interOperation.service';
import { InterOperationService } from './interOperation.service';
export * from './interestRateChart.service';
import { InterestRateChartService } from './interestRateChart.service';
export * from './interestRateSlabAKAInterestBands.service';
import { InterestRateSlabAKAInterestBandsService } from './interestRateSlabAKAInterestBands.service';
export * from './journalEntries.service';
import { JournalEntriesService } from './journalEntries.service';
export * from './likelihood.service';
import { LikelihoodService } from './likelihood.service';
export * from './listReportMailingJobHistory.service';
import { ListReportMailingJobHistoryService } from './listReportMailingJobHistory.service';
export * from './loanAccountLock.service';
import { LoanAccountLockService } from './loanAccountLock.service';
export * from './loanCOBCatchUp.service';
import { LoanCOBCatchUpService } from './loanCOBCatchUp.service';
export * from './loanCharges.service';
import { LoanChargesService } from './loanCharges.service';
export * from './loanCollateral.service';
import { LoanCollateralService } from './loanCollateral.service';
export * from './loanCollateralManagement.service';
import { LoanCollateralManagementService } from './loanCollateralManagement.service';
export * from './loanDisbursementDetails.service';
import { LoanDisbursementDetailsService } from './loanDisbursementDetails.service';
export * from './loanProducts.service';
import { LoanProductsService } from './loanProducts.service';
export * from './loanRescheduling.service';
import { LoanReschedulingService } from './loanRescheduling.service';
export * from './loanTransactions.service';
import { LoanTransactionsService } from './loanTransactions.service';
export * from './loans.service';
import { LoansService } from './loans.service';
export * from './makerCheckerOr4EyeFunctionality.service';
import { MakerCheckerOr4EyeFunctionalityService } from './makerCheckerOr4EyeFunctionality.service';
export * from './mappingFinancialActivitiesToAccounts.service';
import { MappingFinancialActivitiesToAccountsService } from './mappingFinancialActivitiesToAccounts.service';
export * from './meetings.service';
import { MeetingsService } from './meetings.service';
export * from './mixMapping.service';
import { MixMappingService } from './mixMapping.service';
export * from './mixReport.service';
import { MixReportService } from './mixReport.service';
export * from './mixTaxonomy.service';
import { MixTaxonomyService } from './mixTaxonomy.service';
export * from './notes.service';
import { NotesService } from './notes.service';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './offices.service';
import { OfficesService } from './offices.service';
export * from './passwordPreferences.service';
import { PasswordPreferencesService } from './passwordPreferences.service';
export * from './paymentType.service';
import { PaymentTypeService } from './paymentType.service';
export * from './periodicAccrualAccounting.service';
import { PeriodicAccrualAccountingService } from './periodicAccrualAccounting.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './pocket.service';
import { PocketService } from './pocket.service';
export * from './povertyLine.service';
import { PovertyLineService } from './povertyLine.service';
export * from './productMix.service';
import { ProductMixService } from './productMix.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './provisioningCategory.service';
import { ProvisioningCategoryService } from './provisioningCategory.service';
export * from './provisioningCriteria.service';
import { ProvisioningCriteriaService } from './provisioningCriteria.service';
export * from './provisioningEntries.service';
import { ProvisioningEntriesService } from './provisioningEntries.service';
export * from './rate.service';
import { RateService } from './rate.service';
export * from './recurringDepositAccount.service';
import { RecurringDepositAccountService } from './recurringDepositAccount.service';
export * from './recurringDepositAccountTransactions.service';
import { RecurringDepositAccountTransactionsService } from './recurringDepositAccountTransactions.service';
export * from './recurringDepositProduct.service';
import { RecurringDepositProductService } from './recurringDepositProduct.service';
export * from './repaymentWithPostDatedChecks.service';
import { RepaymentWithPostDatedChecksService } from './repaymentWithPostDatedChecks.service';
export * from './reportMailingJobs.service';
import { ReportMailingJobsService } from './reportMailingJobs.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './rescheduleLoans.service';
import { RescheduleLoansService } from './rescheduleLoans.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './runReports.service';
import { RunReportsService } from './runReports.service';
export * from './sCHEDULERJOB.service';
import { SCHEDULERJOBService } from './sCHEDULERJOB.service';
export * from './sMS.service';
import { SMSService } from './sMS.service';
export * from './sPMAPILookUpTable.service';
import { SPMAPILookUpTableService } from './sPMAPILookUpTable.service';
export * from './savingsAccount.service';
import { SavingsAccountService } from './savingsAccount.service';
export * from './savingsAccountTransactions.service';
import { SavingsAccountTransactionsService } from './savingsAccountTransactions.service';
export * from './savingsCharges.service';
import { SavingsChargesService } from './savingsCharges.service';
export * from './savingsProduct.service';
import { SavingsProductService } from './savingsProduct.service';
export * from './scheduler.service';
import { SchedulerService } from './scheduler.service';
export * from './scoreCard.service';
import { ScoreCardService } from './scoreCard.service';
export * from './searchAPI.service';
import { SearchAPIService } from './searchAPI.service';
export * from './selfAccountTransfer.service';
import { SelfAccountTransferService } from './selfAccountTransfer.service';
export * from './selfAuthentication.service';
import { SelfAuthenticationService } from './selfAuthentication.service';
export * from './selfClient.service';
import { SelfClientService } from './selfClient.service';
export * from './selfDividend.service';
import { SelfDividendService } from './selfDividend.service';
export * from './selfLoanProducts.service';
import { SelfLoanProductsService } from './selfLoanProducts.service';
export * from './selfLoans.service';
import { SelfLoansService } from './selfLoans.service';
export * from './selfRunReport.service';
import { SelfRunReportService } from './selfRunReport.service';
export * from './selfSavingsAccount.service';
import { SelfSavingsAccountService } from './selfSavingsAccount.service';
export * from './selfSavingsProducts.service';
import { SelfSavingsProductsService } from './selfSavingsProducts.service';
export * from './selfScoreCard.service';
import { SelfScoreCardService } from './selfScoreCard.service';
export * from './selfServiceRegistration.service';
import { SelfServiceRegistrationService } from './selfServiceRegistration.service';
export * from './selfShareAccounts.service';
import { SelfShareAccountsService } from './selfShareAccounts.service';
export * from './selfShareProducts.service';
import { SelfShareProductsService } from './selfShareProducts.service';
export * from './selfSpm.service';
import { SelfSpmService } from './selfSpm.service';
export * from './selfThirdPartyTransfer.service';
import { SelfThirdPartyTransferService } from './selfThirdPartyTransfer.service';
export * from './selfUser.service';
import { SelfUserService } from './selfUser.service';
export * from './selfUserDetails.service';
import { SelfUserDetailsService } from './selfUserDetails.service';
export * from './shareAccount.service';
import { ShareAccountService } from './shareAccount.service';
export * from './spmSurveys.service';
import { SpmSurveysService } from './spmSurveys.service';
export * from './staff.service';
import { StaffService } from './staff.service';
export * from './standingInstructions.service';
import { StandingInstructionsService } from './standingInstructions.service';
export * from './standingInstructionsHistory.service';
import { StandingInstructionsHistoryService } from './standingInstructionsHistory.service';
export * from './survey.service';
import { SurveyService } from './survey.service';
export * from './taxComponents.service';
import { TaxComponentsService } from './taxComponents.service';
export * from './taxGroup.service';
import { TaxGroupService } from './taxGroup.service';
export * from './tellerCashManagement.service';
import { TellerCashManagementService } from './tellerCashManagement.service';
export * from './twoFactor.service';
import { TwoFactorService } from './twoFactor.service';
export * from './userGeneratedDocuments.service';
import { UserGeneratedDocumentsService } from './userGeneratedDocuments.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './workingDays.service';
import { WorkingDaysService } from './workingDays.service';
export const APIS = [AccountNumberFormatService, AccountTransfersService, AccountingClosureService, AccountingRulesService, AdhocQueryApiService, AuditsService, AuthenticationHTTPBasicService, BatchAPIService, BulkImportService, BulkLoansService, BusinessDateManagementService, BusinessStepConfigurationService, CacheService, CalendarService, CashierJournalsService, CashiersService, CentersService, ChargesService, ClientService, ClientChargesService, ClientCollateralManagementService, ClientFamilyMemberService, ClientIdentifierService, ClientSearchV2Service, ClientTransactionService, ClientsAddressService, CodeValuesService, CodesService, CollateralManagementService, CollectionSheetService, CreditBureauConfigurationService, CurrencyService, DataTablesService, DefaultService, DelinquencyRangeAndBucketsManagementService, DepositAccountOnHoldFundTransactionsService, DeviceRegistrationService, DocumentsService, EntityDataTableService, EntityFieldConfigurationService, ExternalAssetOwnersService, ExternalEventConfigurationService, ExternalServicesService, FetchAuthenticatedUserDetailsService, FineractEntityService, FixedDepositAccountService, FixedDepositAccountTransactionsService, FixedDepositProductService, FloatingRatesService, FundsService, GeneralLedgerAccountService, GlobalConfigurationService, GroupsService, GroupsLevelService, GuarantorsService, HolidaysService, HooksService, InlineJobService, InstanceModeService, InterOperationService, InterestRateChartService, InterestRateSlabAKAInterestBandsService, JournalEntriesService, LikelihoodService, ListReportMailingJobHistoryService, LoanAccountLockService, LoanCOBCatchUpService, LoanChargesService, LoanCollateralService, LoanCollateralManagementService, LoanDisbursementDetailsService, LoanProductsService, LoanReschedulingService, LoanTransactionsService, LoansService, MakerCheckerOr4EyeFunctionalityService, MappingFinancialActivitiesToAccountsService, MeetingsService, MixMappingService, MixReportService, MixTaxonomyService, NotesService, NotificationService, OfficesService, PasswordPreferencesService, PaymentTypeService, PeriodicAccrualAccountingService, PermissionsService, PocketService, PovertyLineService, ProductMixService, ProductsService, ProvisioningCategoryService, ProvisioningCriteriaService, ProvisioningEntriesService, RateService, RecurringDepositAccountService, RecurringDepositAccountTransactionsService, RecurringDepositProductService, RepaymentWithPostDatedChecksService, ReportMailingJobsService, ReportsService, RescheduleLoansService, RolesService, RunReportsService, SCHEDULERJOBService, SMSService, SPMAPILookUpTableService, SavingsAccountService, SavingsAccountTransactionsService, SavingsChargesService, SavingsProductService, SchedulerService, ScoreCardService, SearchAPIService, SelfAccountTransferService, SelfAuthenticationService, SelfClientService, SelfDividendService, SelfLoanProductsService, SelfLoansService, SelfRunReportService, SelfSavingsAccountService, SelfSavingsProductsService, SelfScoreCardService, SelfServiceRegistrationService, SelfShareAccountsService, SelfShareProductsService, SelfSpmService, SelfThirdPartyTransferService, SelfUserService, SelfUserDetailsService, ShareAccountService, SpmSurveysService, StaffService, StandingInstructionsService, StandingInstructionsHistoryService, SurveyService, TaxComponentsService, TaxGroupService, TellerCashManagementService, TwoFactorService, UserGeneratedDocumentsService, UsersService, WorkingDaysService];
