/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BodyPartMediaType } from './bodyPartMediaType';
import { ParameterizedHeader } from './parameterizedHeader';
import { MultiPart } from './multiPart';
import { ContentDisposition } from './contentDisposition';

export interface BodyPart {
  contentDisposition?: ContentDisposition;
  entity?: object;
  headers?: { [key: string]: Array<string> };
  mediaType?: BodyPartMediaType;
  messageBodyWorkers?: object;
  parent?: MultiPart;
  providers?: object;
  parameterizedHeaders?: { [key: string]: Array<ParameterizedHeader> };
}
