/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FinancialActivityData {
  id?: number;
  name?: string;
  mappedGLAccountType?: FinancialActivityData.MappedGLAccountTypeEnum;
}
export namespace FinancialActivityData {
  export const MappedGLAccountTypeEnum = {
    Asset: 'ASSET',
    Liability: 'LIABILITY',
    Equity: 'EQUITY',
    Income: 'INCOME',
    Expense: 'EXPENSE'
  } as const;
  export type MappedGLAccountTypeEnum = (typeof MappedGLAccountTypeEnum)[keyof typeof MappedGLAccountTypeEnum];
}
