/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAccountTransfersTemplateRefundByTransferFromOffice } from './getAccountTransfersTemplateRefundByTransferFromOffice';
import { GetAccountTransfersTemplateRefundByTransferToAccount } from './getAccountTransfersTemplateRefundByTransferToAccount';
import { GetAccountTransfersTemplateRefundByTransferFromAccountOptions } from './getAccountTransfersTemplateRefundByTransferFromAccountOptions';
import { GetAccountTransfersPageItemsToAccountType } from './getAccountTransfersPageItemsToAccountType';
import { GetAccountTransfersTemplateRefundByTransferCurrency } from './getAccountTransfersTemplateRefundByTransferCurrency';
import { GetAccountTransfersTemplateRefundByTransferFromOfficeOptions } from './getAccountTransfersTemplateRefundByTransferFromOfficeOptions';
import { GetAccountTransfersTemplateRefundByTransferFromAccount } from './getAccountTransfersTemplateRefundByTransferFromAccount';
import { GetAccountTransfersTemplateRefundByTransferFromClientOptions } from './getAccountTransfersTemplateRefundByTransferFromClientOptions';
import { GetAccountTransfersFromAccountType } from './getAccountTransfersFromAccountType';
import { GetAccountTransfersTemplateRefundByTransferFromClient } from './getAccountTransfersTemplateRefundByTransferFromClient';
import { GetAccountTransfersTemplateRefundByTransferToClient } from './getAccountTransfersTemplateRefundByTransferToClient';

/**
 * GetAccountTransfersTemplateRefundByTransferResponse
 */
export interface GetAccountTransfersTemplateRefundByTransferResponse {
  currency?: GetAccountTransfersTemplateRefundByTransferCurrency;
  transferAmount?: number;
  transferDate?: string;
  fromOffice?: GetAccountTransfersTemplateRefundByTransferFromOffice;
  fromClient?: GetAccountTransfersTemplateRefundByTransferFromClient;
  fromAccountType?: GetAccountTransfersPageItemsToAccountType;
  fromAccount?: GetAccountTransfersTemplateRefundByTransferFromAccount;
  toOffice?: GetAccountTransfersTemplateRefundByTransferFromOffice;
  toClient?: GetAccountTransfersTemplateRefundByTransferToClient;
  toAccountType?: GetAccountTransfersFromAccountType;
  toAccount?: GetAccountTransfersTemplateRefundByTransferToAccount;
  fromOfficeOptions?: Set<GetAccountTransfersTemplateRefundByTransferFromOfficeOptions>;
  fromClientOptions?: Set<GetAccountTransfersTemplateRefundByTransferFromClientOptions>;
  fromAccountTypeOptions?: Set<GetAccountTransfersFromAccountType>;
  fromAccountOptions?: Set<GetAccountTransfersTemplateRefundByTransferFromAccountOptions>;
  toOfficeOptions?: Set<GetAccountTransfersTemplateRefundByTransferFromOfficeOptions>;
  toClientOptions?: Set<GetAccountTransfersTemplateRefundByTransferFromClientOptions>;
  toAccountTypeOptions?: Set<GetAccountTransfersFromAccountType>;
  toAccountOptions?: Set<GetAccountTransfersTemplateRefundByTransferToAccount>;
}
