/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GetAccountTransfersFromOffice {
  id?: number;
  name?: string;
  nameDecorated?: string;
  externalId?: number;
  openingDate?: string;
  hierarchy?: string;
}
