/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GetAccountsStatus {
  id?: number;
  code?: string;
  description?: string;
  submittedAndPendingApproval?: boolean;
  approved?: boolean;
  rejected?: boolean;
  active?: boolean;
  closed?: boolean;
}
