/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetCentersOfficeOptions } from './getCentersOfficeOptions';
import { GetCentersStaffOptions } from './getCentersStaffOptions';

/**
 * GetCentersTemplateResponse
 */
export interface GetCentersTemplateResponse {
  active?: boolean;
  activationDate?: string;
  officeId?: number;
  officeOptions?: Set<GetCentersOfficeOptions>;
  staffOptions?: Set<GetCentersStaffOptions>;
}
