/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * GetGLClosureResponse
 */
export interface GetGlClosureResponse {
  id?: number;
  officeId?: number;
  officeName?: string;
  closingDate?: string;
  deleted?: boolean;
  createdDate?: string;
  lastUpdatedDate?: string;
  createdByUserId?: number;
  createdByUsername?: string;
  lastUpdatedByUserId?: number;
  lastUpdatedByUsername?: string;
  comments?: string;
}
