/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GLAccountData } from './gLAccountData';
import { CodeValueData } from './codeValueData';
import { EnumOptionData } from './enumOptionData';

/**
 * GetGLAccountsTemplateResponse
 */
export interface GetGLAccountsTemplateResponse {
  disabled?: boolean;
  manualEntriesAllowed?: boolean;
  type?: EnumOptionData;
  usage?: EnumOptionData;
  accountTypeOptions?: Array<EnumOptionData>;
  usageOptions?: Array<EnumOptionData>;
  assetHeaderAccountOptions?: Array<GLAccountData>;
  liabilityHeaderAccountOptions?: Array<GLAccountData>;
  equityHeaderAccountOptions?: Array<GLAccountData>;
  expenseHeaderAccountOptions?: Array<GLAccountData>;
  allowedAssetsTagOptions?: Array<CodeValueData>;
  allowedLiabilitiesTagOptions?: Array<CodeValueData>;
  allowedEquityTagOptions?: Array<CodeValueData>;
  allowedIncomeTagOptions?: Array<CodeValueData>;
  allowedExpensesTagOptions?: Array<CodeValueData>;
}
