/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlobalConfigurationPropertyData } from './globalConfigurationPropertyData';

/**
 * GetGlobalConfigurationsResponse
 */
export interface GetGlobalConfigurationsResponse {
  globalConfiguration?: Array<GlobalConfigurationPropertyData>;
}
