/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetGroupsTemplateDatatables } from './getGroupsTemplateDatatables';
import { GetGroupsTemplateOfficeOptions } from './getGroupsTemplateOfficeOptions';
import { GetGroupsTemplateClientOptions } from './getGroupsTemplateClientOptions';
import { GetGroupsTemplateStaffOptions } from './getGroupsTemplateStaffOptions';

/**
 * GetGroupsTemplateResponse
 */
export interface GetGroupsTemplateResponse {
  officeId?: number;
  officeOptions?: Set<GetGroupsTemplateOfficeOptions>;
  staffOptions?: Set<GetGroupsTemplateStaffOptions>;
  clientOptions?: Set<GetGroupsTemplateClientOptions>;
  datatables?: Set<GetGroupsTemplateDatatables>;
}
