/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HookTemplateData } from './hookTemplateData';
import { Grouping } from './grouping';

/**
 * GetHookTemplateResponse
 */
export interface GetHookTemplateResponse {
  templates?: Array<HookTemplateData>;
  groupings?: Array<Grouping>;
}
