/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetInterestRateChartsChartIdChartSlabsAttributeName } from './getInterestRateChartsChartIdChartSlabsAttributeName';
import { GetInterestRateChartsChartIdChartSlabsConditionType } from './getInterestRateChartsChartIdChartSlabsConditionType';
import { GetInterestRateChartsChartIdChartSlabsIncentiveType } from './getInterestRateChartsChartIdChartSlabsIncentiveType';
import { GetInterestRateChartsChartIdChartSlabsEntityType } from './getInterestRateChartsChartIdChartSlabsEntityType';

export interface GetInterestRateChartsChartIdChartSlabsIncentives {
  id?: number;
  entityType?: GetInterestRateChartsChartIdChartSlabsEntityType;
  attributeName?: GetInterestRateChartsChartIdChartSlabsAttributeName;
  conditionType?: GetInterestRateChartsChartIdChartSlabsConditionType;
  attributeValue?: number;
  attributeValueDesc?: string;
  incentiveType?: GetInterestRateChartsChartIdChartSlabsIncentiveType;
  amount?: number;
}
