/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoanChargeCalculationType } from './getLoanChargeCalculationType';
import { GetLoanChargeCurrency } from './getLoanChargeCurrency';
import { GetLoanChargeTimeType } from './getLoanChargeTimeType';

/**
 * GetLoansLoanIdChargesChargeIdResponse
 */
export interface GetLoansLoanIdChargesChargeIdResponse {
  id?: number;
  chargeId?: number;
  name?: string;
  chargeTimeType?: GetLoanChargeTimeType;
  chargeCalculationType?: GetLoanChargeCalculationType;
  percentage?: number;
  amountPercentageAppliedTo?: number;
  currency?: GetLoanChargeCurrency;
  amount?: number;
  amountPaid?: number;
  amountWaived?: number;
  amountWrittenOff?: number;
  amountOutstanding?: number;
  amountOrPercentage?: number;
  penalty?: boolean;
}
