/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetToClientStandingInstructionSwagger } from './getToClientStandingInstructionSwagger';
import { GetStatusStandingInstructionSwagger } from './getStatusStandingInstructionSwagger';
import { GetToAccountStandingInstructionSwagger } from './getToAccountStandingInstructionSwagger';
import { GetFromAccountTypeStandingInstructionSwagger } from './getFromAccountTypeStandingInstructionSwagger';
import { GetRecurrenceFrequencyStandingInstructionSwagger } from './getRecurrenceFrequencyStandingInstructionSwagger';
import { GetRecurrenceTypeStandingInstructionSwagger } from './getRecurrenceTypeStandingInstructionSwagger';
import { GetFromOfficeStandingInstructionSwagger } from './getFromOfficeStandingInstructionSwagger';
import { GetToAccountTypeStandingInstructionSwagger } from './getToAccountTypeStandingInstructionSwagger';
import { GetFromAccountStandingInstructionSwagger } from './getFromAccountStandingInstructionSwagger';
import { GetPriorityStandingInstructionSwagger } from './getPriorityStandingInstructionSwagger';
import { GetToOfficeStandingInstructionSwagger } from './getToOfficeStandingInstructionSwagger';
import { GetFromClientStandingInstructionSwagger } from './getFromClientStandingInstructionSwagger';
import { GetTransferTypeStandingInstructionSwagger } from './getTransferTypeStandingInstructionSwagger';
import { GetInstructionTypeStandingInstructionSwagger } from './getInstructionTypeStandingInstructionSwagger';

export interface GetPageItemsStandingInstructionSwagger {
  id?: number;
  accountDetailId?: number;
  name?: string;
  fromOffice?: GetFromOfficeStandingInstructionSwagger;
  fromClient?: GetFromClientStandingInstructionSwagger;
  fromAccountType?: GetFromAccountTypeStandingInstructionSwagger;
  fromAccount?: GetFromAccountStandingInstructionSwagger;
  toOffice?: GetToOfficeStandingInstructionSwagger;
  toClient?: GetToClientStandingInstructionSwagger;
  toAccountType?: GetToAccountTypeStandingInstructionSwagger;
  toAccount?: GetToAccountStandingInstructionSwagger;
  transferType?: GetTransferTypeStandingInstructionSwagger;
  priority?: GetPriorityStandingInstructionSwagger;
  instructionType?: GetInstructionTypeStandingInstructionSwagger;
  status?: GetStatusStandingInstructionSwagger;
  amount?: number;
  validFrom?: string;
  recurrenceType?: GetRecurrenceTypeStandingInstructionSwagger;
  recurrenceFrequency?: GetRecurrenceFrequencyStandingInstructionSwagger;
  recurrenceInterval?: number;
  recurrenceOnMonthDay?: string;
}
