/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetRecurringDepositProductsProductIdIncomeFromPenaltyAccount } from './getRecurringDepositProductsProductIdIncomeFromPenaltyAccount';
import { GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappingsCharge } from './getRecurringDepositProductsProductIdPenaltyToIncomeAccountMappingsCharge';

export interface GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappings {
  charge?: GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappingsCharge;
  incomeAccount?: GetRecurringDepositProductsProductIdIncomeFromPenaltyAccount;
}
