/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetRunReportColumnHeaders } from './getRunReportColumnHeaders';
import { GetPocketData } from './getPocketData';

/**
 * GetRunReportResponse
 */
export interface GetRunReportResponse {
  columnHeaders?: Set<GetRunReportColumnHeaders>;
  data?: Set<GetPocketData>;
}
