/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';

/**
 * GetReportMailingJobsResponse
 */
export interface GetReportMailingJobsResponse {
  id?: number;
  name?: string;
  description?: string;
  startDateTime?: string;
  recurrence?: string;
  timeline?: object;
  emailRecipients?: string;
  emailSubject?: string;
  emailMessage?: string;
  emailAttachmentFileFormat?: EnumOptionData;
  stretchyReport?: object;
  stretchyReportParamMap?: string;
  nextRunDateTime?: string;
  numberOfRuns?: number;
  isActive?: boolean;
  runAsUserId?: number;
}
