/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetRecurringDepositAccountsMaxDepositTermType } from './getRecurringDepositAccountsMaxDepositTermType';
import { GetRecurringDepositAccountsSummary } from './getRecurringDepositAccountsSummary';
import { GetRecurringDepositAccountsInterestCalculationType } from './getRecurringDepositAccountsInterestCalculationType';
import { GetRecurringDepositAccountsMinDepositTermType } from './getRecurringDepositAccountsMinDepositTermType';
import { GetRecurringDepositAccountsDepositPeriodFrequency } from './getRecurringDepositAccountsDepositPeriodFrequency';
import { GetRecurringDepositAccountsRecurringDepositFrequencyType } from './getRecurringDepositAccountsRecurringDepositFrequencyType';
import { GetRecurringDepositAccountsStatus } from './getRecurringDepositAccountsStatus';
import { GetRecurringDepositAccountsCurrency } from './getRecurringDepositAccountsCurrency';
import { GetRecurringDepositAccountsInterestPostingPeriodType } from './getRecurringDepositAccountsInterestPostingPeriodType';
import { GetRecurringDepositAccountsInterestCalculationDaysInYearType } from './getRecurringDepositAccountsInterestCalculationDaysInYearType';
import { GetRecurringDepositAccountsTimeline } from './getRecurringDepositAccountsTimeline';
import { GetRecurringDepositAccountsInterestCompoundingPeriodType } from './getRecurringDepositAccountsInterestCompoundingPeriodType';

/**
 * GetRecurringDepositAccountsResponse
 */
export interface GetRecurringDepositAccountsResponse {
  id?: number;
  accountNo?: number;
  clientId?: number;
  clientName?: string;
  savingsProductId?: number;
  savingsProductName?: string;
  fieldOfficerId?: number;
  status?: GetRecurringDepositAccountsStatus;
  timeline?: GetRecurringDepositAccountsTimeline;
  currency?: GetRecurringDepositAccountsCurrency;
  interestCompoundingPeriodType?: GetRecurringDepositAccountsInterestCompoundingPeriodType;
  interestPostingPeriodType?: GetRecurringDepositAccountsInterestPostingPeriodType;
  interestCalculationType?: GetRecurringDepositAccountsInterestCalculationType;
  interestCalculationDaysInYearType?: GetRecurringDepositAccountsInterestCalculationDaysInYearType;
  summary?: GetRecurringDepositAccountsSummary;
  depositAmount?: number;
  maturityAmount?: number;
  maturityDate?: string;
  recurringDepositAmount?: number;
  recurringDepositFrequency?: number;
  recurringDepositFrequencyType?: GetRecurringDepositAccountsRecurringDepositFrequencyType;
  preClosurePenalApplicable?: boolean;
  minDepositTerm?: number;
  maxDepositTerm?: number;
  minDepositTermType?: GetRecurringDepositAccountsMinDepositTermType;
  maxDepositTermType?: GetRecurringDepositAccountsMaxDepositTermType;
  depositPeriod?: number;
  depositPeriodFrequency?: GetRecurringDepositAccountsDepositPeriodFrequency;
}
