/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetRecurringDepositProductsProductIdMinDepositTermType } from './getRecurringDepositProductsProductIdMinDepositTermType';
import { GetRecurringDepositProductsProductIdFeeToIncomeAccountMappings } from './getRecurringDepositProductsProductIdFeeToIncomeAccountMappings';
import { GetRecurringDepositProductsProductIdInterestCompoundingPeriodType } from './getRecurringDepositProductsProductIdInterestCompoundingPeriodType';
import { GetRecurringDepositProductsProductIdMaxDepositTermType } from './getRecurringDepositProductsProductIdMaxDepositTermType';
import { GetRecurringDepositProductsRecurringDepositFrequencyType } from './getRecurringDepositProductsRecurringDepositFrequencyType';
import { GetRecurringDepositProductsProductIdCurrency } from './getRecurringDepositProductsProductIdCurrency';
import { GetRecurringDepositProductsProductIdAccountingMappings } from './getRecurringDepositProductsProductIdAccountingMappings';
import { GetRecurringDepositProductsInterestPostingPeriodType } from './getRecurringDepositProductsInterestPostingPeriodType';
import { GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappings } from './getRecurringDepositProductsProductIdPenaltyToIncomeAccountMappings';
import { GetRecurringDepositProductsInterestCalculationType } from './getRecurringDepositProductsInterestCalculationType';
import { GetRecurringDepositProductsProductIdPreClosurePenalInterestOnType } from './getRecurringDepositProductsProductIdPreClosurePenalInterestOnType';
import { GetRecurringDepositProductsProductIdActiveChart } from './getRecurringDepositProductsProductIdActiveChart';
import { GetRecurringDepositProductsInterestCalculationDaysInYearType } from './getRecurringDepositProductsInterestCalculationDaysInYearType';

/**
 * GetRecurringDepositProductsProductIdResponse
 */
export interface GetRecurringDepositProductsProductIdResponse {
  id?: number;
  name?: string;
  shortName?: string;
  description?: string;
  currency?: GetRecurringDepositProductsProductIdCurrency;
  interestCompoundingPeriodType?: GetRecurringDepositProductsProductIdInterestCompoundingPeriodType;
  interestPostingPeriodType?: GetRecurringDepositProductsInterestPostingPeriodType;
  interestCalculationType?: GetRecurringDepositProductsInterestCalculationType;
  interestCalculationDaysInYearType?: GetRecurringDepositProductsInterestCalculationDaysInYearType;
  accountingMappings?: GetRecurringDepositProductsProductIdAccountingMappings;
  feeToIncomeAccountMappings?: Set<GetRecurringDepositProductsProductIdFeeToIncomeAccountMappings>;
  penaltyToIncomeAccountMappings?: Set<GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappings>;
  recurringDepositFrequency?: number;
  recurringDepositFrequencyType?: GetRecurringDepositProductsRecurringDepositFrequencyType;
  preClosurePenalApplicable?: boolean;
  preClosurePenalInterest?: number;
  preClosurePenalInterestOnType?: GetRecurringDepositProductsProductIdPreClosurePenalInterestOnType;
  minDepositTerm?: number;
  minDepositTermType?: GetRecurringDepositProductsProductIdMinDepositTermType;
  maxDepositTerm?: number;
  maxDepositTermType?: GetRecurringDepositProductsProductIdMaxDepositTermType;
  activeChart?: GetRecurringDepositProductsProductIdActiveChart;
}
