/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSavingsProductsLiabilityUsage } from './getSavingsProductsLiabilityUsage';
import { GetSavingsProductsIncomeType } from './getSavingsProductsIncomeType';

export interface GetSavingsProductsIncomeAccountOptions {
  id?: number;
  name?: string;
  glCode?: number;
  disabled?: boolean;
  manualEntriesAllowed?: boolean;
  type?: GetSavingsProductsIncomeType;
  usage?: GetSavingsProductsLiabilityUsage;
  tagId?: object;
}
