/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSavingsProductOptions } from './getSavingsProductOptions';

/**
 * GetSavingsAccountsTemplateResponse
 */
export interface GetSavingsAccountsTemplateResponse {
  clientId?: number;
  clientName?: string;
  productOptions?: Set<GetSavingsProductOptions>;
}
