/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSelfClientsStatus } from './getSelfClientsStatus';

export interface GetSelfClientsPageItems {
  id?: number;
  accountNo?: number;
  status?: GetSelfClientsStatus;
  active?: boolean;
  activationDate?: string;
  fullname?: string;
  displayName?: string;
  officeId?: number;
  officeName?: string;
}
