/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetChargesChargeCalculationType } from './getChargesChargeCalculationType';
import { GetChargesChargeTimeType } from './getChargesChargeTimeType';
import { GetChargesCurrencyResponse } from './getChargesCurrencyResponse';

/**
 * GetSavingsAccountsSavingsAccountIdChargesResponse
 */
export interface GetSavingsAccountsSavingsAccountIdChargesResponse {
  id?: number;
  chargeId?: number;
  accountId?: number;
  name?: string;
  chargeTimeType?: GetChargesChargeTimeType;
  chargeCalculationType?: GetChargesChargeCalculationType;
  percentage?: number;
  amountPercentageAppliedTo?: number;
  currency?: GetChargesCurrencyResponse;
  amount?: number;
  amountPaid?: number;
  amountWaived?: number;
  amountWrittenOff?: number;
  amountOutstanding?: number;
  amountOrPercentage?: number;
  penalty?: boolean;
}
