/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TemplateMapper } from './templateMapper';

/**
 * GetTemplatesResponse
 */
export interface GetTemplatesResponse {
  id?: number;
  name?: string;
  entity?: number;
  type?: number;
  text?: string;
  mappers?: Array<TemplateMapper>;
}
