/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InteropIdentifierRequestData {
  idType: InteropIdentifierRequestData.IdTypeEnum;
  idValue: string;
  subIdOrType?: string;
  accountId: string;
}
export namespace InteropIdentifierRequestData {
  export const IdTypeEnum = {
    Msisdn: 'MSISDN',
    Email: 'EMAIL',
    PersonalId: 'PERSONAL_ID',
    Business: 'BUSINESS',
    Device: 'DEVICE',
    AccountId: 'ACCOUNT_ID',
    Iban: 'IBAN',
    Alias: 'ALIAS'
  } as const;
  export type IdTypeEnum = (typeof IdTypeEnum)[keyof typeof IdTypeEnum];
}
