/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PostLoansLoanIdChargesChargeIdResponse
 */
export interface PostLoansLoanIdChargesChargeIdResponse {
  officeId?: number;
  clientId?: number;
  loanId?: number;
  savingsId?: number;
  resourceId?: number;
}
