/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostFixedDepositProductsCharts } from './postFixedDepositProductsCharts';

/**
 * PostFixedDepositProductsRequest
 */
export interface PostFixedDepositProductsRequest {
  name?: string;
  shortName?: string;
  description?: string;
  currencyCode?: string;
  digitsAfterDecimal?: number;
  inMultiplesOf?: number;
  locale?: string;
  interestCompoundingPeriodType?: number;
  interestPostingPeriodType?: number;
  interestCalculationType?: number;
  interestCalculationDaysInYearType?: number;
  accountingRule?: number;
  preClosurePenalApplicable?: boolean;
  preClosurePenalInterest?: number;
  preClosurePenalInterestOnTypeId?: number;
  minDepositTerm?: number;
  minDepositTermTypeId?: number;
  maxDepositTerm?: number;
  maxDepositTermTypeId?: number;
  charts?: Set<PostFixedDepositProductsCharts>;
}
