/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PostLoansLoanIdTransactionsTransactionIdRequest
 */
export interface PostLoansLoanIdTransactionsTransactionIdRequest {
  locale?: string;
  dateFormat?: string;
  transactionDate?: string;
  transactionAmount?: number;
  note?: string;
}
