/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * runaccrualsRequest
 */
export interface PostRunaccrualsRequest {
  locale?: string;
  dateFormat?: string;
  /**
   * which specifies periodic accruals should happen till the given Date
   */
  tillDate: string;
}
