/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PostUsersRequest
 */
export interface PostUsersRequest {
  username?: string;
  firstname?: string;
  lastname?: string;
  email?: string;
  officeId?: number;
  staffId?: number;
  roles?: string;
  sendPasswordToEmail?: boolean;
  isSelfServiceUser?: boolean;
}
