/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Changes } from './changes';

/**
 * PutChargeTransactionChangesResponse
 */
export interface PutChargeTransactionChangesResponse {
  resourceId?: number;
  loanId?: number;
  changes?: Changes;
}
