/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PutDataTablesAppTableIdDatatableIdRequest
 */
export interface PutDataTablesAppTableIdDatatableIdRequest {
  DateOfBirth?: string;
  Education_cdHighest?: number;
  Name?: string;
  OtherNotes?: string;
  PointsScore?: number;
  dateFormat?: string;
  locale?: string;
}
