/**
 * Apache Fineract
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Question } from './question';

export interface Response {
  id?: number;
  question?: Question;
  text?: string;
  value?: number;
  sequenceNo?: number;
  new?: boolean;
}
